umap-project/umap

- setup.py
On Debian Jessie with pip install :
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-o_ERWm-build/setup.py", line 16, in <module>
with open('requirements.txt', encoding='utf-8') as reqs:
TypeError: 'encoding' is an invalid keyword argument for this function
> Correct setup.py

- README.md
The previous link was redirecting to an inexisting content > changed.
> Change wrong link to RDTD documentation

- umap/settings/base.py
Swap this wiki link to httpS
The wiki is now on httpS and sadly the httpS redirect causes #anchor links to be lost
> fix feedback anchor link to wiki (httpS)

- requirements.txt
openstreetmap.org switched to https://
login with umap does not work anymore with old
social-auth version. The new version now has the
https:// urls.
> bump social-auth to use https:// for osm.org oauth

- umap/management/commands/import_pictograms.py
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/js/umap.permissions.js
- umap/templates/umap/about_summary.html
It seems mistakes in the original English (en) translation strings are
not fixed in the website despite them being correct for en_US in
Transifex for several years. My guess is that they are the default for
en, so unless you somehow manage to explicitly select en_US (which does
not seem possible), you are stuck with the incorrect English.
> Fix original English translation strings

- umap/static/umap/js/umap.controls.js
I tested locally, the iframe and the See full screen are working great.
Here is a sample of generated code fro iframe
> <iframe width="100%" height="300px" frameborder="0" allowfullscreen src="//localhost:8000/en/map/test-cyclosm_1?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe><p>
And for the full screen link: 
> `<a href="//localhost:8000/en/map/test-cyclosm_1">See full screen</a></p>`
Note that in source code `baseUrl` is only used for iframe src url, nothing else.
BTW, this PR is related to the proposal i made in #662
> Remove protocol from iframe src url

- docs/administration.md
- docs/contributing.md
- docs/install.md
- docs/ubuntu.md
- mkdocs.yml
Hi, i will use this PR in order to ask other users to review my changes.
So it's not necessary to merge it quickly, cause i will continue to improve it.
> Improve documentation

- umap/settings/base.py
- umap/utils.py
Here is a fix for the issue #302 (changing username in OSM do not sync in uMap).
I tracked this problem deep down the following issues:
-  python-social-auth/social-core#263
-  python-social-auth/social-core#348
This issue is related to the fact that in "Python Social Auth - Core", the field "username" is protected and can not be updated. So if you change your username in OSM, GitHub, BitBucket or Twitter, it will never be synced in uMap. :disappointed:
The best solution is a fix in "Python Social Auth - Core", we should allow developers to ignore those "default protected fields", i will probably make a PR to social-core.
So i made a workaround in uMap to fix this issue and it is working nicely. To do so, iI defined my own [pipeline](https://python-social-auth.readthedocs.io/en/latest/pipe …
> Update username with value from OAuth provider

- umap/settings/base.py
cf https://github.com/django/django/blob/master/django/conf/locale/__init__.py#L10
"get_language_info_list" would not run otherwise.
> Add "si" to LANG_INFO

- umap/static/umap/map.css
Not sure why I didn't fix that before, sounds like an easy fix. So maybe there is a trap I forgotten since then…
Before:
After:
fix #143
> Set icon img max-height

- umap/static/umap/js/umap.features.js
- umap/static/umap/test/Feature.js
fix #737
This allows to use variables in the `labelKey` field, eg. `Foo {var1} ({var2})`, and it will be used wherever we display a "feature label".
> Allow variables in tooltips

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/js/umap.slideshow.js
- umap/static/umap/js/umap.xhr.js
That may need a bit more thinking, but that may also be a good starting point:
- every feature has a unique identifier, based on one of its properties (by default: name)
- this property name can be changed in the map settings
- when exporting to iframe, there is now an option to include the current feature
- on right click on a feature, there is a "permalink" action
fix #497
fix #294
> Feature permalink

- requirements.txt
Bump Pillow version to 8.0.1
Pillow version >= 8.0 is mandatory for python3.9 (default python version on current Ubuntu LTS 20.04
> Update requirements.txt for Pillow with python3.9

- umap/static/umap/js/umap.core.js
- umap/static/umap/test/Util.js
The new 'coalesce feature' from issue #820 was mentioned at our latest (virtual) [Swiss/Zurich OSM meeting](https://wiki.openstreetmap.org/wiki/DE:Switzerland:Z%C3%BCrich/OSM-Treffen#124._OSM-Stammtisch_Fr._11._Dezember_2020). However, it did not seem to work at all on [our](https://umap.osm.ch/) uMap instance. Although this turned out to have been a simple deployment issue, when looking at the code, I also noticed a small implementation error which made it always use the last fallback if there were any, even if the first property lookup or any of the previous fallbacks returned a defined value. I also noticed that the characters that could be used in the static fallback were quite limited such that the original example from issue #820 would not have worked (even when adapted to the final …
> Fix and enhance property fallbacks

- umap/settings/local.py.sample
setting "SOCIAL_AUTH_REDIRECT_IS_HTTPS = True" per https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#processing-redirects-and-urlopen with a view of resolving https://github.com/umap-project/umap/issues/846
> redirect users back to TLS version of umap after 3rd party auth.

- umap/static/umap/map.css
Whenever the key or value is too long, the table was pushed being wider than the given container. And the overflow rules cut off the content of the table.
Fixes
- Remove overflow rules (reset to defaults, which is `auto`), which makes a scroll bar show up if content is too wide
- Let long text break in lines instead of pushing the table (which in turn prevents the scroll bar from showing up)
Test case: https://umap.openstreetmap.de/de/map/version-2-zes-datenprufung-oberflachen_20496#12/52.3474/13.6080
| before | after |
|---|---|
|  <img width="426" alt="Bildschirmfoto 2021-12-22 um 14 43 12" src="https://user-images.githubusercontent.com/111561/147102523-7e45a0c5-78ca-46b5-a6c2-52e616eae8cf.png"> |  <img width="594" alt="Bildschirmfoto 2021-12-22 um 14 43 18" …
> CSS: Fix cut of text in table of popup content

- umap/static/umap/base.css
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
- umap/static/umap/locale/fr.js
- umap/static/umap/locale/fr.json
- umap/static/umap/map.css
This pull request is divided into 3 separated commits:
1. Filters checkboxes using features' properties (the user sets which properties should be used for filtering in the map options, then checkboxes appear in the filtering tab)
2. Permanent credits feature in the bottom left corner (the user writes those credits from the map settings, like other credits, and has the ability to hide the permanent credit's background, for example, to only show an image/logo)
3. Interface option to hide caption menus (interface option to hide menus in the caption bar: "Browse data", "Filter data", "About" and "Home")
> New asked features: checkbox filters, permanent credits, and caption menus options

- umap/tests/test_map_views.py
- umap/views.py
The default django.core.signing Signer uses SHA256 algorithm since Django 3. Umap used Django 2 in the paste, so people had SHA1 signed anonymous edit URLs, which became unusable when umap switch to Django 3. This commit makes them usable again (the new SHA256-signed anonymous edit URLs still works, obviously).
> 🐛 — Allow to use SHA1-signed anonymous edit URL

- umap/views.py
It should not have any performance issue given that we paginate over the list anyway.
Fix #1025
> Remove the limit of visible maps in user’s view

- umap/static/umap/js/umap.controls.js
The list can be pretty big (like on OSMfr):
> Lazy load tile layers thumbnails

- umap/static/umap/js/umap.js
Refs #713, otherwise that first message is displayed and then override by the map creation one.
> Do not display an alert if the map is not created

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
I missed that one and I fixed a bug in the meantime setting a correct label (vs. invisible placeholder for an input of type range).
I set a fallback on the datalist id in case no label is specified (which is probably not a good idea).
> Follow up on #1090 for overlay’s opacity

- package-lock.json
- package.json
- umap/static/umap/test/Controls.js
- umap/static/umap/test/DataLayer.js
- umap/static/umap/test/Feature.js
- umap/static/umap/test/Map.js
- umap/static/umap/test/Marker.js
- umap/static/umap/test/Permissions.js
- umap/static/umap/test/TableEditor.js
- umap/static/umap/test/_pre.js
- umap/static/umap/test/index.html
Since this commit https://github.com/umap-project/umap/commit/97e2df0a8d698d1a9a531447db360187062a4843 tests were broken because the URL has an extra date parameter to update the cache for datalayers. With the new regexp, we match these new URLs with the fakeServer from sinon.
Also update sinon to v15.
> Fix JS tests

- docs/install.md
- umap/forms.py
- umap/management/commands/anonymous_edit_url.py
- umap/models.py
- umap/settings/base.py
- umap/static/umap/base.css
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.ui.js
- umap/tests/settings.py
- umap/tests/test_map_views.py
- umap/urls.py
- umap/views.py
This is a work I started last year, and not yet finished.
The goal is to add a button "Send me the link" when creating a map in anonymous mode.
> Add a button to send edit link by email in anonymous mode

- umap/settings/base.py
It’s more convenient to let the sub-themes declare their own templates (especially with `'APP_DIRS': True`).
> Remove `DIRS` from `settings.TEMPLATES`

- umap/static/umap/map.css
This is a proposed change to resize the list of layers to fit the content of the list by default and give the ability to resize the window.
I felt that I was constrained by the fixed size that wasn't displaying enough layers to be comfortable to use.
> Ability to resize the list of layers displayed on the map

- umap/static/umap/content.css
- umap/templates/umap/content.html
- umap/templates/umap/messages.html
Messages are already shown in the map, if any.
Useful in our case when an error is raised by the auth flow.
> Show messages also in the content part

- umap/static/umap/font.css
> Gives the font face an extremely small block period and an infinite swap period. — https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#values
Extracted from https://github.com/umap-project/umap/pull/1093
> Set `font-display: swap;` for fonts definition

- umap/static/umap/js/umap.controls.js
- umap/static/umap/test/DataLayer.js
- umap/static/umap/test/_pre.js
Before:
After:
Background polygons (which layer is set to "non browsable") are still visible even if they do not match the active filter.
> Advanced filter should not affect non browsable layers

- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/test/Feature.js
- umap/static/umap/test/_pre.js
Useful for example to adapt the outgoing link according to current user locale
fix #183
> Expose 'locale' parameter in templates

- umap/static/umap/js/umap.js
fix #1042
Until now, we create an empty datalayer (which has some defaults), then we overwrite the options while calling fromGeoJSON method
> Pass options at datalayer creation when importing from umap file

- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/js/umap.popup.js
- umap/static/umap/test/Util.js
This PR does two things:
- make the outlink available for any feature, not only polygon: which is, one can define a link that will be opened when clicking on the feature (instead of opening a popup) cf #323 
- use the `outlinkTarget` option to also control where popup links will be opened (self/blank/parent) cf #869 
fix #869
> Control links target

- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.icon.js
- umap/static/umap/test/DataLayer.js
cf #858
I've created a new function `getSmartOption`, that extends `getOption`, so to use it explicitly for now. We may at some point make that `getOption` is always smart, but let's be a bit conservative here…
> Allow to use properties as color value

- umap/settings/__init__.py
Trying to install umap on Debian Bookworm (12) with custom templates gave me this error when trying to do `umap migrate`:
```
Loaded local config from /var/www/umap/local.py 
Traceback (most recent call last):                                                            
File "/var/www/umap/venv-bookworm/bin/umap", line 8, in <module>
sys.exit(main())                      
^^^^^^               
File "/var/www/umap/venv-bookworm/lib/python3.11/site-packages/umap/bin/__init__.py", line 12, in main
management.execute_from_command_line()                                                    
File "/var/www/umap/venv-bookworm/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
utility.execute() …
```
> 🐛 — Fix UMAP_CUSTOM_TEMPLATES setting

- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.js
- umap/views.py
We use locale name (pt_PT) instead of the language code to use in localeCompare, which is wrong.
Given that both need to exist, let's also expose it in extendedProperties.
fix #1187
> Use LANGUAGE_CODE instead of locale name for browser APIs

- umap/static/umap/js/umap.layer.js
> Display time in datalayer versions list

- umap/static/umap/js/umap.features.js
This is a change in Leaflet 1.7.0
cf https://github.com/Leaflet/Leaflet/issues/7302
Before:
After:
> Fix tooltip anchor not updated anymore according to the direction

- umap/templates/umap/login_popup_end.html
Now that we have a dashboard page, this makes more sense than the "public profile" page.
> Fallback user to dashboard after OAuth process

- umap/views.py
This view should not be used in production, but it is sometimes, so just in case…
> Add a timeout in proxy

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.popup.js
This is since recent Leaflet upgrade.
The issue was:
- clicking on feature in the data browser replaces the panel content
- then the clicked link (the feature name or the little glass icon) is removed
- thus it is detached from the DOM
- and specially from its parent on which disableClickPropagation was called
- so Leaflet fails to prevent click propagation
- so the map received the click, and thus it call the onRemove method on
the panel, as expected (clicking on the map always close the current
open popup, if any)
This could be removed when this is released:
https://github.com/Leaflet/Leaflet/pull/9052
Before:
[Screencast from 2023-07-31 21-09-38.webm](https://github.com/umap-project/umap/assets/146023/4420015e-b048-4ef3-86a4-a91beb61fa93)
After:
[Screencast from 2023-07-31 …
> Fix popup panel not opening from the data browser

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
fix #40
Let the user choose the map behaviour to define default view:
- saved center and zoom: current behaviour, and default
- bounds: will compute the view to fit all the map data, useful for having the same view in different sized devices (mobile…)
- latest feature: useful in some situation, where the map tracks some progress (travel…), this will certainly needs a bit more iterations, mainly to have an explicit default datalayer
- user location: this option used to exist but was then removed, I can remember when and why
Note: when there is a URL hash, the hash will be used
> Better control of default view

- umap/static/umap/base.css
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/map.css
- umap/static/umap/test/DataLayer.js
- adding/removing of feature was managed directly in the control, which should not be case, this is fixed, and this is now done by the datalayer
- instead of creating a new form element from scratch, we reuse Leaflet.FormBuilder
- rename "advanced filters / data filter" by "Facet search"
I'd love to have a look at this with @Aurelie-Jallut, but in a later step.
> Refactor "advanced filters" (and rename to facets)

- umap/static/umap/map.css
> adapt iframe min-width for popup large

- README.md
- umap/settings/base.py
- umap/static/umap/js/umap.controls.js
- umap/templates/umap/content_footer.html
Hello 👋 
Small fix and maybe you prefer that i link to this page https://umap-project.readthedocs.io/en/master/changelog/
but as it was not really up to date i chose to go for github and to link to the specific version  :) 
but i'm ready to change if you prefer
Regards
> fix: correct changelog link

- docs/requirements.txt
- mkdocs.yml
> Use magiclink extension for changelog with links

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
- umap/static/umap/test/Map.Init.js
- umap/static/umap/test/_pre.js
- umap/static/umap/test/index.html
We want to init the map view once, in our initCenter method, so we remove any center from the option, to prevent Leaflet to init the map on this centers
fix #1277
closes #1281 
closes #1282
> Remove default center to prevent multiple map initialisations

- docs/ubuntu.md
- umap/views.py
uMap allows to use remote URL as data sources, but those URLs are not always CORS open, so this is why there is this "ajax-proxy" feature, where the URL is passed to the backend.
Additionally, there is a caching feature, which duration is configurable through frontend settings. Valid values are: disabled, 5 min, 1 hour, 1 day.
Initially, I wanted this to be totally handled by Nginx, but I never found a wayt to set the proxy_cache_valid value from a query string.
Since then, at least in OSM France servers, the ajax-proxy is still handled by a Django view, which then opens the remote URL and transfert the data. This is not optimal. And I suppose this is what is causing hicups on the OSM France servers lately.
This PR provides a mix option, where python deals with validating the URL and …
> Use X-Accel-Redirect for serving ajax-proxy request

- umap/static/umap/js/umap.js
It's not supported anymore by browsers.
> Remove custom message from onbeforeunload event

- umap/views.py
Only use the content type with mimetypes.guess_type
> Avoid using a tuple as a content type when guessed

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/map.css
While changing the edit header help link, I've changed all help buttons, which was not intended.
Before:
After:
> Restore help button icon

- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
This occurs when the remote datalayer has a min or maxZoom defined, and the map is loaded outside those zooms. In this case, when calling fetchRemoteData, the fetch was never done, nor the final call to fromGeoJSON, which would have sent the dataloaded event.
> Try to fix remote datalayer not sending dataloaded

- docs/settings.md
- docs/ubuntu.md
Here's a summary of the changes and why
* added 'apt update' before the install -- only _needed_ on a completely fresh VM, but never hurts
* added an install of the virtualenv package, because it is used later but: do you still need it AND python3-venv? I'm assuming it was done that way for a reason.
* changed indentation on the mkdir so it will format correctly
* added `-D ~postgres` to the commands executed as postgres user because the postgres user does not, by default, have permission to read into real user's home directories (at least in 22.04) and so the commands would error out
* change `source <activate>` to `. activate` because the line `sudo -u umap -i` launches `sh`, not `bash`, and `sh` does not recognize the source command. `.` works in either.
* remove the instructions to …
> Ran through the 'Ubuntu from Scratch' procedure using a fresh Ubuntu 22.04.3 LTS VM and took notes on what worked and what didn't.

- docker-compose.yml
- docker/entrypoint.sh
- pyproject.toml
- umap/settings/base.py
I just got started with umap using docker.  Even though the entrypoint has a mechanism to wait for the database, it wasn't waiting.
Docker compose now supports depends_on with a healthcheck.   I feel it's better to use this declarative configuration over imperative bash.
Side note, if this was the only reason "umap shell" exists, then please also close that entry point to remove the attack vector.
> Replace wait_for_database with depends_on and healthcheck.

- package-lock.json
- package.json
- umap/static/umap/base.css
- umap/static/umap/js/umap.js
> Restrict possible min/max zoom values

- umap/static/umap/map.css
Until now, the width was computed on the fly by Leaflet, based on the popup content, but this leads to a bunch of issue on image/iframe width.
Before:
After:
cf https://forum.openstreetmap.fr/t/bugs-divers-relevees-sur-une-umap-absent-sur-une-autre/17254/8
> Set an explicit width to popup large container

- umap/static/umap/js/umap.js
This may happen if:
- the map as some layers containing data, but set as not browsable
- any other layer is empty
> Do no try to fit data bounds if bounds are not valid

- umap/static/umap/map.css
The star indicating a dirty map uses more than 5px (depending on font-size). So the additional star switched from showing the map name to ellipses-overflow in px-implementation.
1ch is the with of the digit '0'.
So the issue in #1308 is not about max-width but also reproducible for very short map names.
Nevertheless max-width of 200px for a.map-name seems a bit restrictive for desktop browsers and could be increased?!
Replaces #1310
> Fix map's title when “dirty star” is present

- umap/static/umap/js/umap.js
- umap/tests/integration/test_owned_map.py
We don't want those link to be shared.
> Redirect to canonical when URL contains the ?edit parameter

- docker/uwsgi.ini
Prevents issues as described in #1353
> Update uwsgi.ini to prevent buffers errors with NGINX reverse proxies

- umap/static/umap/base.css
to allow multi-line texts in translations
in svedish and german translation the buttons for "Open link in..." are longer. This results in multiline-buttons that the fixed height cannot handle.
I first thought about shortening translations - but how can one make sure, that every string in every language fits within the buttons? Thus I suggest to switch to the `grid` layout, which is already used by the button-bar. 
The only difference between `.button-bar` and `.umap-multiplechoice` is now the grid-gap.
> switch to grid layout for multiple choice buttons

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.layer.js
- umap/tests/base.py
- umap/tests/integration/test_map.py
In some situations, we don't want all datalayers to be displayed in the caption list, for example because the layer only contains "non meaningful" data: aesthetics one, or technical, or administrative…
Not sure about the property name…
> Allow to hide a datalayer from the caption list

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.layer.js
A bunch of improvement to make heatmap layers more usable:
- fix issues in Range input
- use a Range for heatmap radius
- use patch from https://github.com/Leaflet/Leaflet.heat/pull/78
Before:
After:
> Heatmap improvements

- umap/static/umap/js/umap.layer.js
In some situation, the property is undefined, given the call is async, and we can add/remove the layer during the async stack
> Add back HeatLayer._map reference check

- umap/static/umap/base.css
This is what is currently visible (1px of the next icon):
For instance if I put 44px, it's more visible:
Now this is the fix:
There is no small fix, hey!
> Hide the next icon in buttons’ sprites

- umap/static/umap/js/umap.features.js
It may happen when data comes from an import.
fix #1377
> Fix filter data crashing when data contains non string values

- umap/static/umap/js/umap.js
Even if this limit is not a hard limit, just a warning, we now have been proven some maps using custom backgrounds use zooms greater than 20.
Eg. this maps which allows zoom until 23:
https://umap.openstreetmap.fr/fr/map/cimetiere-asnieres-la-giraud_716488
> Increase maxZoomLimit to 24

- umap/static/umap/js/umap.forms.js
Before:
After:
I don't think we really have cases where we'd need 2 digits rounding.
> Round range step to 1 digit

- umap/static/umap/js/umap.js
Keep together "shape" related properties, so in the default properties we don't need to do a redraw.
> Keep only non graphic props in default properties, to prevent useless redraw

- umap/static/umap/js/umap.js
This can have an impact in map listing, because dataToload will be shared.
> Fix variable declared globally by mistake

- umap/static/umap/js/umap.layer.js
This occurs when the cluster layer has a min/maxZoom defined, the map is loaded inside this zoom range BUT the defaultView=data, and would immediately change the current zoom to a value outside this range.
In this case, the datalayer is added to the map, then the data is requested, then the map view is recomputed with the full data bounds.
There may be a better fix on our side, but given there is async in the middle, it can be time consuming and can add complexity (with more events and listeners) to properly make it work.
> Fix race condition with cluster layer

- umap/static/umap/base.css
`umap-alert` is set on the body to show/hide the alert container, so it's to wide:
fix #1398
> Fix wrong css selector for umap-alert-container elements

- umap/static/umap/content.css
- umap/static/umap/nav.css
Before:
After:
This time, baked by @Aurelie-Jallut 😇
> Improve buttons’ contrasts on the homepage #a11y

- docs/install.md
Sadly, when using a SearchVector, Django will introduce a COALESCE that will then prevent our index to be used. So we need to add this COALESCE in the index to make psql happy.
fix #1414
> Update search index command in documentation

- package.json
- umap/static/umap/js/umap.features.js
This is fixed in Leaflet.FormBuilder itself.
Spotted here yesterday:
> Use step=any by default for FloatInput

- umap/static/umap/base.css
- umap/static/umap/js/umap.js
- umap/static/umap/map.css
- umap/tests/base.py
- umap/tests/integration/test_slideshow.py
Those button, being width: 100% and display: block were not displayed AND were pushing out also the slideshow buttons.
Before:
After:
> Restore missing buttons in caption bar

- umap/static/umap/map.css
There are some usage with 5 chars that do not fit anymore. Let's reset for now and maybe introduce later a way for the user to configure the size.
See also https://lists.openstreetmap.org/pipermail/umap/2023-November/000545.html
> Reset increasing icon text size

- umap/static/umap/js/umap.js
There is an edge case when using "locate" a default view AND activating easing for transitions: in this case, Leaflet.locate needs a  "starting view" to compute the easing to the new position (the user location).
I could have only set the default_view when easing is on, but I thought it was simpler to just set it anyway…
> Set map default center even if waiting for user location

- umap/static/umap/js/umap.layer.js
- umap/static/umap/map.css
I guess we forgot this when switching from `a` to `button`
> Restore style of "restore version button"

- umap/static/umap/js/umap.tableeditor.js
Adding a property when table is not in fullwidth is buguish, so let's make it simple.
In the future, we'd replace this table editor with a dedicated lib.
cf #1363
> Always use fullwidth table editor

- umap/static/umap/js/umap.layer.js
- umap/tests/test_datalayer_views.py
- umap/tests/test_merge_features.py
- umap/utils.py
- umap/views.py
original code from @Biondilbiondo (Thanks! :) )
Basically:
- when there is a conflict (i.e. someone try to save with an old ETag)
- we compare new version with its reference version and with the latest known
- if we see only simple case (features added both side, removal on one side…),
then we merge
- otherwise we raise the conflict as before
> Optimistic conflicts resolution mecanism

- umap/static/umap/js/umap.js
When facet search is set as the default panel, if using remote data, no filter data was appearing in the panel.
> fix: no data in facet filters when set as default panel

- docs/requirements.txt
I didn't catch that docs has a separated requirements.txt file for readthedocs.
> [chore] fix docs requirements

- .github/workflows/test-docs.yml
This adds a separate target for docs, to ensure that the docs will be build the same way readthedocs does it.
> [ci] Add a separate target for docs

- docs/changelog.md
- mkdocs.yml
> Better changelog rendering

- umap/static/umap/js/umap.layer.js
When DataLayer._dataloaded is set, DataLayer.addLayer will send 'datachanged' event (for once for each feature). When the data browser panel is open, the browser is listening to 'datachanged' to rebuild itself.
Not sure this is the real final fix, but that may need more refactoring, so I think this approach is already a better situation than the current.
fix #1457
> Make sure DataLayer._dataloaded is set only once all data is imported

- umap/static/umap/js/umap.controls.js
It fails on this._map being undefined, and it's useless.
> Do not call AttributionControl._update for removed tile layer

- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.js
- umap/tests/base.py
- umap/tests/integration/test_export_map.py
- umap/tests/integration/test_map.py
- umap/tests/test_map_views.py
Here is the initial issue:
- when using defaultView=latest (means latest element of the default layer)
- when map loads, we find the element, call getCenter to center the map on it
- but Polygon/Polyline needs the element to be already on the map to call
this method (at least because the map CRS is needed)
So while trying to fix that issue, I also found that using a centroid for
a complex geometry was not very friendly: the map zoom on a part of this
geometry, while it seems to be that it's better to have a full view of it.
Now that we highlight the selected element, it's also easier to get which
element is focused when there are a lot close one to the others.
> Use bounds instead of center when zooming to Polyline/Polygon

- umap/static/umap/base.css
> Fix toolbox overflow with facets’ search

- umap/tests/base.py
- umap/tests/integration/test_export_map.py
- umap/tests/test_map_views.py
It's easier to debug integration tests screenshots (otherwise background is only grey).
> Use real tile URL in tests

- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.layer.js
This flag deactivate all interactions for a path. It can be useful when some polygon is used to delimitate an area on the map, but when we don't want this area to be clickable.
I've a case where I've many of those polygons in a given map, and they are imported, so I don't want to go one by one to deactivate it.
As a side effect, this option will also be available for lines.
> Allow to control the `interactive` option from the layer

- package-lock.json
- package.json
- scripts/vendorsjs.sh
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/static/umap/map.css
- umap/static/umap/test/index.html
- umap/templates/umap/css.html
- umap/templates/umap/js.html
[Screencast from 2023-12-15 11-35-56.webm](https://github.com/umap-project/umap/assets/146023/89f823fe-0bea-41f6-a7ab-29207ffc05a7)
> Use Leaflet.IconLayers as tilelayers switcher

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/tests/integration/test_tilelayer.py
Found some edge cases of the new tilelayer switcher this morning while testing it a bit more:
- when importing a map with a background not in the 10 first layers
- when choosing a tilelayer after the 10 first from the selector in edit mode
A bit of prettier noise…
> Iconlayers polish

- Makefile
- umap/models.py
Following the discussion on #1471, here are proposed changes to the `Makefile`.
- Runs a subprocess, and setup a trap to ensure ctrl+c can stop the server
- Uses [`python -m webbrowser`](https://docs.python.org/3/library/webbrowser.html) to open a new tab (cross compatible)
> build: Update makefile testjs to open the browser

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/tests/integration/test_drawing.py
With previous fix (in 60c002f94a80ef03a91edcd5c8d6019a59a07cd0), the feature was created even if invalid.
cf #1428
> Better way of handling escape while drawing

- umap/static/umap/js/umap.core.js
Quick fix for not failing with an error in case of #1481
> Do not fail on greedyTemplate when description is an object

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
This is not the ideal fix, instead we'd prefer to use `TileLayer.getTileUrl`, but this is not possible yet.
cf https://github.com/Leaflet/Leaflet/pull/9201
cf https://lists.openstreetmap.org/pipermail/umap/2023-December/000557.html
> Fix preview of TMS TileLayer preview

- umap/static/umap/map.css
In some situation, the preview is very similar to the background, so it's not visible enough.
fix #1485
> Add a small box-shadow to tilelayer preview

- umap/static/umap/js/umap.controls.js
The index of the top layer in the view starts with zero, while the rank of the layers count backwards. Thus moving the second-last to the last position should set the dirty flag of rank 0 and 1. Instead the former implementation set the dirty flag for layers >= 5, when moving "Red" to the bottom in [the test map](https://umap.openstreetmap.fr/fr/map/test-ordering_994821) - resulting in the wrong layers saved.
Fixes #375
> fix dirty flags when re-ordering layers

- umap/static/umap/base.css
- umap/static/umap/img/16.svg
- umap/static/umap/img/source/16.svg
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.share.js
- umap/static/umap/map.css
- umap/static/umap/test/Map.Export.js
- umap/static/umap/test/index.html
- umap/templates/umap/js.html
- umap/tests/integration/test_export_map.py
**Is your feature request related to a problem? Please describe.**
Users of our map often complain they didn't find the gpx download option. We embed a umap on our club website. But having to click the share button to download, then scroll down and find the `geojson` dropdown to select `gpx` seems to be not really intuitive.
**Describe the solution you'd like**
We'd like to have an intuitive, easy-to-use download option of gpx files.
**Describe alternatives you've considered**
* Splitting the gpx / kml download option into a "download" dialog with download-icon would probably be most intuitive. But further increasing the number of buttons on the left hand side and an essentially empty dialog seems not the way to go.
* Add gpx output to the new server API could be an option, so that we …
> Refactor Share & Download UI for better usability

- umap/static/umap/js/umap.layer.js
The `postUpdate` method of the Choropleth layer is called after any form field change, even if this field is not in the dedicated choropleth helper. So the previous check was too broad, and it would try to fetch the breaks input value on any form helper, which would fail if someone change any "non choropleth" property (like the colour)
> Be more explicit on changed fields when updating choropleth form

- package-lock.json
- package.json
- umap/static/umap/js/umap.controls.js
When entering a string in a form of a latlng, we'll do two things:
- add a result that allow to center the map on this latlng (and to create a new point if edit mode is enabled)
- do a reverse search and display it result if any
fix #1000
cf #1001
> Allow to type a latlng in the search box

- umap/models.py
- umap/static/umap/content.css
- umap/static/umap/js/umap.ui.js
- umap/templates/auth/user_form.html
- umap/templates/umap/content.html
- umap/templates/umap/map_list.html
- umap/templates/umap/map_table.html
- umap/templates/umap/user_dashboard.html
- umap/templatetags/umap_tags.py
- umap/utils.py
- umap/views.py
Refs #1459
This is a proposal to reduce the size/time for that view. The map is only loaded when the user clicks the Preview button.
Before:
After:
The preview opens in an almost full-screen dialog element with blurred background:
Let's discuss :) Once accepted, I'll put styles and scripts to their regular places.
> Preview map only on click in user’s dashboard

- README.md
I've removed the badges:
- Travis is not used anymore
- The gitter room has been replaced by one on matrix.org
- The doc is now hosted on the `docs.` subdomain
I've replaced the badges by links to:
- our website
- the matrix.org room
- the mailing list
Let me know if I missed something?
> docs: Update the links in the README, remove the badges

- umap/static/umap/base.css
- umap/static/umap/js/umap.browser.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.icon.js
- umap/static/umap/js/umap.popup.js
- umap/static/umap/map.css
It's a popup template that know how to display data coming from OpenStreetMap. At this stage, it's very basic and only display contact informations, but I'd like to push such a minimalist version and see how users use it before putting more energy on it.
What's not done and may be in further steps:
- display a i18n label (bakery, swimming pool)
- automatically display an icon if none is set on the layer
- show opening hours, or at least show if the shop/amenity is open
- show more specific tags like the cuisine for a restaurant, the organic tag, etc.
- connect to panoramax/mapilary to have a picture…
There is no intention to cover all and every possible case, but only to focus on the main tags (shop/amenity…).
> Add a popup template to showcase OpenStreetMap data

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.layer.js
- umap/tests/integration/test_edit_datalayer.py
Instead of having them at the end of "Advanced properties", there is now a dedicated box:
cf #1490
> Move layer specific settings to a dedicated fieldset

- .gitignore
- pyproject.toml
- umap/settings/base.py
- umap/settings/local.py.sample
- umap/templates/base.html
- umap/templates/umap/about_summary.html
- umap/templates/umap/content.html
- umap/templates/umap/css.html
- umap/templates/umap/js.html
- umap/templates/umap/map_detail.html
- umap/tests/integration/test_statics.py
- umap/tests/settings.py
- umap/utils.py
This is a really early stage.
The `support_js_module_import_aggregation` toggle + wrong regexps for our prettier semicolons-less config were hard to find!
> Use custom storage instead of django-compressor

- umap/static/umap/js/umap.layer.js
- umap/tests/integration/test_collaborative_editing.py
This happens in collaborative mode only.
`data.geojson` was then add to `this.options` (through the `this.updateOptions(data)`, and thus the `geojson` was then saved in the db settings at next save, and thus served again so the datalayer would reset itself again to that geojson, making new points disappearing.
cf #1536
cf #1537
cf https://forum.openstreetmap.fr/t/probleme-de-sauvegarde-des-cartes/20596 cf https://forum.openstreetmap.fr/t/umap-soucis-de-debutants/20538 cf https://forum.openstreetmap.fr/t/probleme-de-maj-des-icones/20565
> fix: prevent datalayer to resetting to an old version on save

- umap/static/umap/js/umap.browser.js
- umap/tests/integration/test_browser.py
Features title may contain variables, which include geographical ones (center, lat, lon…), and in this case the feature must be on the map to be able to compute them (eg. the polygon center).
fix #1519
> fix: build browser once features are on the map, not before

- umap/static/umap/js/umap.layer.js
It actually does not make sense, and it's a sanity check: some computation algorithms fail in this situation.
> fix: do not ask more classes than available values in choropleth mode

- umap/static/umap/js/umap.js
- umap/tests/integration/test_querystring.py
`datalayersControl` is an exception among the HIDDABLE_CONTROLS: while all other controls have a ternary value true/false/null, it also accepts `expanded`.
I've found cleaner to add an exception in the code instead of trying to factorise the utils for this exception, but this may be discussed. :)
fix #1525
> fix: honour datalayersControl=expanded in querystring

- umap/static/umap/js/umap.importer.js
- umap/tests/integration/test_import.py
Otherwise, we cannot import anything else than a file, even when closing and reopening the panel. User needs to refresh the page.
> fix: empty file input when closing the importer panel

- docs/config/settings.md
- umap/settings/base.py
- umap/templates/umap/home.html
- umap/tests/test_views.py
- umap/views.py
For now we have only three modes:
- latest, which is the default and shows the last updated maps
- highlighted, which shows only the map that have been starred by a least one staff member
- None, which does not show any map
> Introduce UMAP_HOME_FEED to control which maps are shown on the home page

- umap/static/umap/js/umap.features.js
This can happen in a situation where:
- a layer as zoom limits
- we click on a feature, which opens a popup
- then zoom over the layer's limit (with scroll or keyboard, not keyboard, in order to not close the popup)
- then click in anywhere in the map, which will close the popup
Since the highlight of features on click (cf #1359), we redraw them on popupclose, which explains the bug described above.
fix #1575
> fix: do not try to reset tooltip of feature not on map

- docs/config/customize.md
- umap/templates/base.html
- umap/templates/registration/login.html
- umap/templates/umap/content.html
- umap/templates/umap/map_detail.html
We might want to configure it for the JS side too: https://docs.sentry.io/platforms/javascript/
> feat: Adding Sentry errors reporter support

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/js/umap.slideshow.js
- umap/tests/integration/test_browser.py
Also rework the browsable/browse methods to try to make them more understandable…
The core fix is that `isVisible` check is not done anymore when using `eachBrowsableDataLayer`.
fix #1554
> fix: non loaded layers should still be visible in legend and data browser

- umap/static/umap/js/umap.js
- umap/tests/integration/test_map_preview.py
- umap/tests/integration/test_querystring.py
- umap/urls.py
- umap/views.py
This is the same as "map new", but it is not directly in edit mode. This allow to click on the elements and see the popups instead of editing it when using a `dataUrl` query string.
This way of using uMap is not documented, but it's used by some partners (Deveco recently, data.gouv.fr historicaly).
In the same time, this PR adds two things:
- possibility to pass data directly in querystring (instead of an URL): in the case of Deveco, they have pages where only point is shown (for each company)
- possibility to pass style options directly from query string: may allow for example to control the `popupTemplate`, eg. to use a table one that will display all properties of the clicked feature
Note: dataUrl and such also works in normal "map new" view. There are two use cases around those …
> feat: add experimental "map preview" in /map/ endpoint

- umap/static/umap/base.css
- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/modules/global.js
- umap/static/umap/js/modules/request.js
- umap/static/umap/js/umap.browser.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/test/index.html
- umap/tests/integration/test_browser.py
Refactor the way it updates itself in the process and move to a module.
Core changes, out of the refactor, are:
- adding a new DisableClickPropagation to each feature, otherwise there is a race condition, and when clicking on the feature it's a element detached to the DOM, so the click propagation is not stopped, so the map receive the click and close the popup that was about to open
- rework the way the browser listen to the `moveend` event: it known always listen to the event, and decide in the listener to proceed or not. Before we were trying to add and remove the event listerner, but there was edge cases…
> fix: browser inBbox setting not persistent and features click not opening popup

- umap/static/umap/js/umap.core.js
I've been a report about changed pictograms, which pointed to this map:
I found that with those grey, the picto should have been white, so I had a look and increased a bit the threshold.
Before:
After:
> feat: change breakpoint to switch black SVG img to white

- umap/templates/umap/map_detail.html
- umap/tests/test_map_views.py
- umap/views.py
See https://github.com/umap-project/umap/pull/1526#issuecomment-1937040472
I'm not fully sure it'll fix the issue though.
> fix: encode the whole url parameter for OEmbed

- umap/static/umap/js/umap.popup.js
The panel inherits from the classic Popup, but given it's fixed on the UI, it does not make sense to try to move it, and it some situation there is a race condition that make Leaflet try to animate but this fails
> fix: do not try to animate the panel

- LICENSE
Rationale: the WTFPL is not an OSI approved license since it has been rejected as such in 2009 (emphase is mine):
> Title: WTFPL Submission: http://crynwr.com/cgi-bin/ezmlm-cgi?17:mss:634:200902:aglgcgbhmfcheffmdgon License: http://sam.zoy.org/wtfpl/ Comments: It’s no different from dedication to the public domain. Author has submitted license approval request — author is free to make public domain dedication. Although he agrees with the recommendation, Mr. Michlmayr notes that **public domain doesn’t exist in Europe.** Recommend: Reject — https://opensource.org/meeting-minutes/minutes20090304/
This is an issue to be able to apply to some open-source programs and grants.
> Switch license from WTFPL to AGPLv3

- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
When using data/dataUrl querystring, uMap will import data at load, and will set view using this data bounds. In some situation (Deveco), the user wants to control the max zoom of the final view.
Also add labelKey and showLabel to be parsed from query string, still for Deveco needs.
> feat: allow to set zoomTo from query string

- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.icon.js
- umap/tests/integration/test_picto.py
This feature was planned in the initial rework of the pictogram form UI, but not yet done. Some recent discussion in the OSM French forum reactivated the need for it.
cf https://forum.openstreetmap.fr/t/marker-and-marker-colors/21051
> feat: show last used pictograms in a separate tab

- umap/static/umap/js/umap.tableeditor.js
We should use a proper lib for this table editor, but in the meantime…
cf https://github.com/umap-project/umap/issues/1363#issuecomment-1754656244
> fix: reset table editor properties after creating a new one

- umap/storage.py
I'm not totally sure it's the way to go (maybe ignoring here is fine ?), but it seems still more usefull to have a proper error instead of a python error a few lines forward.
> chore: raise error if any in storage post_process

- umap/static/umap/js/umap.forms.js
> fix: picto category title was added after the related pictograms

- umap/tests/integration/test_collaborative_editing.py
- umap/views.py
Previously, an error was thrown when the reference datalayer had no `features`defined.
When looking for features, it now defaults to an empty list if the key doesn't exist.
> fix: allow empty datalayers reference on merges.

- umap/static/umap/js/umap.popup.js
cf #1663
Seems be something `id` sometime `@id`, not sure why (node vs relation ? old vs recent ?). Let's allow both, it's simpler than trying to understand :p
> fix: read id and @id as osm id in osm template

- umap/static/umap/js/modules/global.js
- umap/static/umap/js/modules/utils.js
- umap/static/umap/js/umap.features.js
- umap/tests/integration/test_features_id_generation.py
Add an ID for each feature on creation, or when read from a GeoJSON.
Ids are persisted in the GeoJSON
> chore: add ids on features

- umap/tests/test_merge_features.py
The current code already ensures that items
changed in the reference weren't also changed
in the latest changes, so we are covered.
> chore: ensure merge + assigning ids are rejected

- umap/static/umap/js/umap.layer.js
- umap/templates/umap/js.html
- umap/tests/integration/test_collaborative_editing.py
- umap/tests/test_datalayer_views.py
- umap/views.py
`X-Datalayer-Version` and `X-Datalayer-Reference` are now used instead
of the `Last-Modified` and `If-Unmodified-Since` headers.
`Last-Modified` is granular to the second, which led to problems with
the versionning. The new system uses timestamps instead.
This commit also changes the way versions were created. Previously,
the associated version was coming from two different places:
the last modified time from the filesystem and a `time.time()` call
done when saving the model, which could result in the two getting
out of sync.
> [!NOTE]
> **This still has one issue** Requests coming at the same time can lead to conflicts. It's not clear if we want to create a lock system to handle this, or if we just consider this as an edge case.
-> It seems we want to consider this an edge-case for now, …
> fix: Replace Last-Modified with custom headers

- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/tests/integration/test_map.py
We had an issue (not in Github :p) where a map was not loading because the defaultView was set to "data", and the layers were remote data layers. In this case, when computing the remote URL, we allow to replace georelated variables (like east, west, north, lat…), which needs the map to have a view.
So:
- the default view was expecting the data to be loaded (="data")
- the data to be loaded needed a default view…
So instead of adding yet another call to _setDefaultView in an edge case, we reordered the way we initialize the map elements:
- first we initialize the controls (because initCenter needs the locate control to exist)
- then we call initCenter
- then we initialize the tile layers (because the miniMap needs it to render itself)
- then we call renderControls
> chore: refactor initCenter and controls ordering

- umap/templates/umap/map_table.html
- umap/templatetags/umap_tags.py
- umap/tests/integration/test_dashboard.py
> fix: hide delete button for editors in dashboard

- umap/static/umap/js/umap.importer.js
- umap/tests/integration/test_import.py
Update list when we open the panel instead of only once at build time.
fix #1729
> fix: update layers list in import panel

- umap/static/umap/js/umap.layer.js
Otherwise we lose the browser current context (some layer may be opened, or user may have scrolled down).
`onDataLayersChanged` will make the browser to be redrawn, and it was called anytime `connectToMap` itself was called, which is at datalayer init and datalayer save, but we can only make this call for a new datalayer.
> fix: prevent rebuilding the browser at each save

- umap/models.py
- umap/static/umap/js/umap.js
- umap/tests/integration/test_map_list.py
There was an edge case when map has "dataLayersControl=expanded": we only overrided "onLoadPanel", so dataLayersControl was still considerer. Let's have a more generic stop.
Before:
After:
> fix: make sure we do not render browser in map fragment

- umap/tests/integration/conftest.py
Also, cast the PLAYWRIGHT_TIMEOUT parameter.
> Mock OSM tiles requests in Playwright for speed

- umap/static/umap/js/umap.js
- umap/tests/integration/test_statics.py
And also add a "See layer" action in the context menu.
I'm not totally sure it's the way to go, but it's closer to the current behaviour, and as a user a way missing a way to go straight to the extanded browser version.
> make that "browse data" opens the browser in expanded mode

- umap/static/umap/js/modules/utils.js
- umap/static/umap/js/umap.autocomplete.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.importer.js
- umap/static/umap/js/umap.permissions.js
- umap/static/umap/js/umap.popup.js
- umap/static/umap/js/umap.share.js
- umap/static/umap/js/umap.ui.js
- umap/tests/integration/test_basics.py
- umap/tests/integration/test_tilelayer.py
We have "smart text" attribution in the DB (which translates to raw html), so I guess we're stuck with innerHTML…
> fix: ensure tilelayer attribution with smart text is displayed as HMTL

- scripts/vendorsjs.sh
- umap/static/umap/js/modules/dompurify.js
- umap/static/umap/js/modules/utils.js
It requires a special nginx configuration that we want to avoid for all instances deployments:
```
include mime.types;
types {
application/javascript mjs;
}
```
> fix: no .mjs extension for JS modules

- scripts/vendorsjs.sh
Fix up for  2c1cd46167402d7dca4e4ffb4689ec93ee01e5e8
We keep the `.mjs` fragment within the filename to avoid changing it manually within the renamed `purify.es.js` file. Given the `.map` extension, it will not affect the nginx (or others) mimetypes configuration.
> fix: vendorize the .map too for dompurify

- umap/tests/integration/conftest.py
Some tests randomly fail in the CI because of timeout a bit short.
> chore: try to change Playwright expect timeout

- umap/static/umap/css/panel.css
In some situation in mobile (eg. when the keyboard is used), the screen is still considered as landscape, but it is very small, so make sure the panel does not overflow on the right.
cf #1788
> Add max-width to panel in landscape mode

- umap/static/umap/js/umap.controls.js
The event does not contain latlng, so we cannot compute the line length yet.
> fix: do not try to render drawinTooltip on drawing start

- umap/static/umap/css/panel.css
> fix: adapt panel expanded height when map has a caption bar

- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/tests/integration/test_edit_datalayer.py
But remove from layers list, and make sure browser and caption are up to date.
fix #498
fix #1831
> fix: do not close blindly editPanel when deleting a layer

- umap/static/umap/base.css
Before:
After:
cc @Aurelie-Jallut cf discussion on Mattermost, but so you can have an other look at it
> feat: use accent color for switch and multichoices on dark background

- docs/config/icons.md
- docs/deploy/docker.md
Hi,
after having initial issues with `umap.conf` not being found while using docker container i think it could be helpful to add a few more lines in the `docker.md` for a better start off.
- Added a comment below the `umap.conf` path definition asserting it is an optional setting
- Specified how to create an admin user and how to access it, otherwise you will experience problems in saving maps or adding tile-layers
> Expanded docker.md documentation

- umap/static/umap/base.css
- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/modules/panel.js
- umap/static/umap/js/modules/schema.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.popup.js
- umap/tests/integration/test_browser.py
- umap/tests/integration/test_caption.py
- umap/tests/integration/test_facets_browser.py
- umap/tests/integration/test_view_marker.py
cf https://forum.openstreetmap.fr/t/umap-2-3-changement-de-gestion-des-pop-up/23680/3
Trying to make this panel expanded/condenses thing simpler and more intuitive.
It's mode can be set:
- by explicitely setting defaultPanelMode = xxx
- or, if defaultPanelMode is undefined, with sensible default when there is an onLoadPanel defined, and to respect previous uMap behaviour
- or, if defaultPanelMode is unset, and some feature opens in the panel, it will be set to expanded (here again to respect previous behaviour
- then, when user change it manually (by clicking on the toggle button), then we should never change it automatically, and respect the previous mode when reopening the panel
(We are only talking about the left panel, here.)
> fix: only set panel mode once, and then keep user choice

- umap/static/umap/js/modules/utils.js
- umap/static/umap/map.css
- umap/static/umap/unittests/utils.js
Basically, we do not add `<br>` anymore, but instead let the newline and use the css `white-space: pre-line;`. Also remove new lines after title.
While doing that change, I needed to reorder regex so the ones needing a newline before would still have it (bullets points).
I've added tests and removed some to cover those changes.
fix #1854
> fix: refactor new line management in popups

- umap/static/umap/js/umap.js
> fix: support old storage options when importing a umap file

- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/static/umap/js/modules/sync/websocket.js
- umap/static/umap/unittests/sync.js
Removes the concept of message dispatcher and message sender, all of it can be done by the syncengine class, making it easier to grasp.
> refactoring(sync): Simplify the design of the sync engine.

- umap/static/umap/js/umap.features.js
> fix: use correct icon class in edit feature panel

- umap/static/umap/js/modules/request.js
- umap/templates/umap/content.html
- umap/templates/umap/home.html
- umap/templates/umap/search.html
This used to be the case, but was changed by mistake in the request refactor (switch from xhr)
> fix: display an alert on any request error

- docs-users/fr/support/faq.md
- docs-users/support/faq.md
- umap/static/umap/js/modules/global.js
- umap/static/umap/js/modules/rules.js
- umap/static/umap/js/modules/schema.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/tests/integration/test_conditional_rules.py
> feat: very minimal experimental conditional style rules

- umap/static/umap/js/components/alerts/alert.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
alert.js was importing request.js which then imports alert.js
In the process, we moved the post to send the email out of the alert.js file, and thus tried another pattern to communicate data between an alert and its caller.
> fix: django cannot run collectstatic with circular imports in modules

- umap/static/umap/js/modules/importer.js
> fix: display an alert if the import is successful

- umap/static/umap/js/umap.js
FormBuilder will break when reimporting an exported map with this default value (at the casting to object was only made on the init, so reimporting will override this to null again).
> chore: do not set overlay=null as default

- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/tests/integration/test_browser.py
fix #1908
At some point, we may want to cache the computation of `feature.getDisplayName()`, and maybe `layer.getFilterKeys()`, in case there are hundreds of features it may impact the UI.
> fix: use layer labelKey if any when filtering features

- umap/static/umap/base.css
- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/umap.popup.js
- umap/static/umap/map.css
We removed line breaks management on the JS side so to manage it in CSS, but this CSS was only active on popup/panels for features. Let's have a class for this, and add it to the map description to (about panel).
> fix: also use white-space: pre-line on map description

- umap/static/umap/map.css
Since fa2bef85d3dd6bbe0c39a7dca2def2a2ad1422b3 popup are smaller, let's try to have them as before.
> fix: increase popup min-width

- umap/static/umap/js/umap.js
- umap/tests/integration/test_map.py
> feat: give precedence to feature in query string over onLoadPanel

- umap/static/umap/base.css
- umap/static/umap/content.css
- umap/static/umap/css/dialog.css
- umap/static/umap/css/panel.css
- umap/static/umap/css/tooltip.css
- umap/static/umap/js/components/alerts/alert.css
- umap/static/umap/map.css
- umap/static/umap/vars.css
Positive side-effect (fix): alerts are now above importers panel.
Before:
After:
> chore: rationalize z-indexes in CSS

- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
I found some issues with the current implementation of the sync mechanism, which this PR fixes.
- The "move a feature from one datalayer to another" feature was not thought of, at all, and as a result introduced the bug that was referenced in #1931.
- It turns out that the syncing of this operation wasn't working either, creating shape clones along the way.
- The previous (buggy) implementation was not sending the proper layer id, resulting to features hosted by the wrong layers.
- Operations were triggered when loading data from the original server, which shouldn't happen.
Generally speaking, the current implementation misses some cross-datalayer tests, but I suggest these should come as a separate pull request.
> Multiple sync-related fixes

- biome.json
- umap/static/umap/js/modules/autocomplete.js
- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/modules/dompurify.js
- umap/static/umap/js/modules/facets.js
- umap/static/umap/js/modules/help.js
- umap/static/umap/js/modules/importer.js
- umap/static/umap/js/modules/importers/geodatamine.js
- umap/static/umap/js/modules/orderable.js
- umap/static/umap/js/modules/rules.js
- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/static/umap/js/modules/ui/tooltip.js
- umap/static/umap/js/modules/urls.js
- umap/static/umap/js/modules/utils.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.core.js
- umap/static/umap/js/umap.datalayer.permissions.js
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.icon.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/static/umap/js/umap.permissions.js
- umap/static/umap/js/umap.popup.js
- umap/static/umap/js/umap.share.js
- umap/static/umap/js/umap.slideshow.js
- umap/static/umap/js/umap.tableeditor.js
- umap/static/umap/test/DataLayer.js
> chore: apply Biome unsafe changes

- package.json
- umap/static/umap/js/umap.features.js
- umap/static/umap/js/umap.forms.js
Steps to reproduce:
- click in any BlurInput
- change to any value
- click outside the input => the value will be set to the object
- click again in the input
- change value to the initial
- click outside => the value will not be set
This is because the BlurInput in sync on blur, and it was comparing the current field value with an "initial" one, only set at build. This check is made because we don't want to trigger an edit when a user click in a blurinput and click outside without changing the value.
> fix: BlurInput was not updating the object in some situations

- umap/static/umap/js/modules/autocomplete.js
- umap/static/umap/js/modules/global.js
- umap/static/umap/js/modules/rules.js
- umap/static/umap/js/umap.js
- umap/static/umap/js/umap.layer.js
- umap/tests/integration/test_conditional_rules.py
> feat: add AutocompleteDatalist and use it for conditional rules

- umap/static/umap/js/modules/schema.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
And move properties to shema.js. Given those keys does not have a "guessable" handler, let's have a "customHandlers" prop to deal with those (instead of keeping them outside of the schema…)
fix #2006
> fix: broken sortKey help

- umap/static/umap/js/umap.js
Since 8ddc570e23bc403317b0509f50580af9d077ca86 we lost the link request <=> map, so the "dataloading" and "dataload" events are global to the DOM, so when loading a list of maps, all instances react to all dataloading events, which makes the list a mess.
I'd prefer to keep this loading indicator per map, but it's much easier to just hide it, so let's go that way.
> fix: deactivate loader on map fragments

- .github/workflows/test-docs.yml
So to bump PostgreSQL to 13, and make Django 5.1 happy
> chore: bump postgis in the CI

- umap/settings/base.py
- umap/static/umap/js/modules/permissions.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/templates/registration/login.html
- umap/templates/umap/login_popup_end.html
- umap/tests/integration/test_anonymous_owned_map.py
- umap/tests/integration/test_basics.py
- umap/tests/integration/test_owned_map.py
- umap/views.py
This:
- catch "login_required" from the map page, when hitting the save button
- proceed the save and close the login page at the end of the login process
- make sure to update the map user after a save
It's not ideal because when the save process includes a magic link (which can be the case with MonComptePro eg.), the new window will never be closed, and the save will not proceed, so the user will have to close the new window and click save again. Then the map will save and the user name will be shown in the edit toolbar as normal.
But that's the better compromise I can get to…
> fix: catch login_required from map page and add a way to login

- umap/static/umap/css/slideshow.css
- umap/static/umap/js/modules/rendering/template.js
- umap/static/umap/js/modules/utils.js
Since a2ca3a143615fde971a5f908afae02b0487d62a4, the panel/popup template uses loadTemplate, which used to remove all white spaces from the inner html. We had to do this to workaround white space breaking the slideshow toolbox buttons.
So this commits fixes this problem in another way: do not remove white space (usefull for text content in popup/panels), but use a display: flex instead of inline-block.
Before:
After:
> fix: white space was broken since using loadTemplate

- umap/static/umap/css/tableeditor.css
Otherwise when scrolling the table, the input will not appear at the expected position, and may even appear outside of the view when the table is bigger than the viewport.
Drawback: the table will resize its columns when the input/textarea is created (as block is in the flow). So I've also removed the width reset.
fix #2071
> fix: remove position fixed for input and textarea in tableeditor

- .github/workflows/test-docs.yml
This PR updates checkout and setup-python actions, because versions used in repository use a deprecated version of node js
More information here:
- https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
- [Checkout actions releases](https://github.com/actions/checkout/releases)
- Setup-[python actions releases](https://github.com/actions/setup-python/releases)
> Fix warning in worflows

- umap/static/umap/js/modules/importers/overpass.js
(instead of a long list of "Orange"…)
> feat: add more context in overpass importer autocomplete results

- umap/static/umap/js/umap.controls.js
We were testing the length of the `_layers` property, which where sliced to `maxShown` before…
> fix: tilelayer plus icon were never displayed

- umap/static/umap/js/modules/schema.js
- umap/static/umap/js/umap.js
- umap/tests/integration/test_edit_datalayer.py
- umap/tests/integration/test_querystring.py
This value of datalayersControl exists for retrocompat only (it's now replaced by onLoadPanel=browser)
> fix: make sure datalayersControl=expanded does not override onLoadPanel

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/ui.js
And for now open the properties panel (geometry/position may be edited later, when Leaflet.Editable knows about CircleMarker)
> fix: do not fail when trying to edit a circlemarker

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/ui.js
Otherwise, when using the browser, we'll end up using this._map.getBounds(), but in this case the UI may not be in the map (may be filtered).
> fix: feature.isOnScreen is now passing the "bounds" argument

- umap/decorators.py
- umap/models.py
- umap/templatetags/umap_tags.py
- umap/tests/conftest.py
- umap/tests/test_datalayer.py
- umap/tests/test_map.py
- umap/views.py
In the same move, refactor the can_edit/_view/_delete functions to only take the request, which is what really happen in the code, and adapt the test in that way.
> fix: teams.all() called on anonymous user by mistake

- Makefile
- docs/release.md
So we can integrate the changelog in the release, instead of having a commit after the release.
You need to have a GITHUB_TOKEN env var, with a read only bearer coming from https://github.com/settings/tokens
> chore: get Github release notes from command line

- docs/config/settings.md
- umap/context_processors.py
- umap/settings/base.py
- umap/templates/umap/dashboard_menu.html
- umap/urls.py
In some situations, the profile comes from the OAuth provider and shouldn’t be modified by users.
> feat: add a setting to prevent users from editing their profile

- umap/static/umap/js/modules/data/features.js
The primary coordinates is a two-elements Array in Point.coordinates, but FormBuilder does not know how to edit an Array, so we edit the `ui._latlngs` instead.
The proper fix would have been to teach FormBuilder how to edit an Array, but that path is way longer, and given we plan to refactor it totally, let's wait for that.
fix #2144
> fix: editing coordinates manually would not be saved

- .github/workflows/close-issues.yml
For now, only issues marked with "needs info" or "support" will be affected.
> chore: add a Github action to autoclose issues after some time

- umap/management/commands/clean_tilelayer.py
- umap/tests/test_clean_tilelayer.py
It can be useful to manage the tilelayer registered in the map settings in db.
> chore: add clean_tilelayer management command

- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/hlc.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/static/umap/js/modules/sync/websocket.js
- umap/static/umap/js/modules/utils.js
- umap/static/umap/js/umap.forms.js
- umap/static/umap/js/umap.js
- umap/static/umap/unittests/hlc.js
- umap/static/umap/unittests/sync.js
- umap/static/umap/unittests/utils.js
- umap/tests/integration/test_datalayer.py
- umap/tests/integration/test_import.py
- umap/tests/integration/test_map.py
- umap/tests/integration/test_websocket_sync.py
- umap/tests/test_websocket_server.py
- umap/views.py
- umap/websocket_server.py
Operations are now stored locally in memory. All operations are tied to an HLC (Hybrid Logical Clock), making it possible to order them consistently.
When a new peer join, it asks a random peer for the list of operations, and re-apply them locally.
A new type of message has been introduced, making it possible to relay messages to other peers via the server. Messages types names have been updated to follow CamelCase, and to be similar across the client and the server.
> Send remote operations to peers when they join

- docker/uwsgi.ini
Checks if the `WEBSOCKET_ENABLED` is set to `True` and runs the websocket server accordingly.
> chore(deploy): Spawn the websocket server in the docker image.

- umap/static/umap/js/modules/rendering/ui.js
- umap/tests/integration/test_view_polygon.py
This bug has been introduced when spliting features, as we now only set the Leaflet Polygon options with setStyle, will the `interactive` option is only used in the init by Leaflet.
See https://github.com/Leaflet/Leaflet/pull/9475
> fix: polygon with interactive=false was still interactive

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/ui.js
- umap/static/umap/js/umap.controls.js
- umap/tests/integration/test_circles_layer.py
The main issue was because we overrided the `getLatLngs` function in our PointMixin class, so I changed the way feature get the latlngs from the UI classes. Plus getting CircleMarker to inherit more from Marker, through PointMixin.
fix #2171
> fix: allow to draw new proprotional circles and to drag them

- umap/static/umap/js/umap.js
Let's make it smaller (unless proven otherwise!).
> clean: remove zoom in and out from contextmenu

- umap/static/umap/unittests/hlc.js
Should fix [this error](https://github.com/umap-project/umap/actions/runs/11165503827/job/31037336947?pr=2188)
> tests: use `at.least` to compare dates on the hlc tests.

- umap/static/umap/js/umap.js
Contextmenu and keyboard shortcuts open controls, which are not fully initiated when in mode `noControl`, which is the case for preview.
> chore: deactivate contextmenu and shortcuts in map preview

- umap/static/umap/js/umap.controls.js
fix #2197
The fix here is to add the `text` class, the rest is cleaning.
> fix: honour carriage returns in permanent credits

- umap/static/umap/js/modules/browser.js
> fix: do not show browser counter when layer is empty or not loaded

- umap/static/umap/js/modules/rendering/ui.js
- umap/static/umap/js/umap.js
Do not show generic map items when clicking on a feature.
cf #2109
Click on map:
Click on feature:
> chore: simplify contextmenu items

- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/modules/ui/contextmenu.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/map.css
- umap/tests/integration/test_browser.py
fix #2097
cf #1500
This is an alternative proposal for #2097:
- adding the button near the "Filter" toggle was a bit ugly, CSS/HTML talking, because this "Filters" box is a details/summary
- I thought that other needs could live in the same place: a link to download the filtered/visible data, and a button to show the map data extent
The "toggle all" button works this way:
- if one or more layers are shown, it will hide those layers
- otherwise it will show all layers
I've preferred not to change the button icon according to map state, because I didn't find a reliable way to do so, thus I'm afraid to have inconsistency, but I can't try harder if needed.
Related: I'm thinking of adding a "Download" button for each layers, as it's a request that comes quite often.
@Aurelie-Jallut could you …
> feat: add a global toolbox in browser

- docker-compose.yml
- docs/deploy/docker.md
The top-level 'version' property is deprecated and can be omitted to prevent warnings.
> Docker: `version` is obsolete.

- umap/static/umap/js/umap.core.js
> fix: fix dispeared icons from panel titles

- umap/static/umap/css/importers.css
- umap/static/umap/img/importers/cadastrefr.svg
- umap/static/umap/js/modules/importer.js
- umap/static/umap/js/modules/importers/cadastrefr.js
- umap/static/umap/js/modules/importers/communesfr.js
> feat: add importer for French cadastre

- umap/static/umap/js/umap.js
Otherwise the renderEditToolbar will reset name and all.
fix #2225
> fix: always call propagate at end of save

- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/rendering/layers/classified.js
- umap/static/umap/map.css
- umap/tests/integration/test_caption.py
fix #2232
A classified layer needs to have compiled the data to known its classes/categories.
This commit review the way we build the legend: instead of creating with the whole caption panel, we just set a container and we populate it later. This opens the door for live changing the legend when editing the layer.
But we have to clarify that "reactive" pattern at some point, as we have some concurrent pattern laying around: the `render()`, which coupled with the schema and this is nice, but for now it's a bit rough (changing the whole UI each time); the `propagate` way, which is more specific, but not coupled to the schema; the `dataChanged`; and the `onDataLoaded` now, which is a bit different, as it's about the data being loaded, not changed/modified, but for the DOM it may at the end be …
> fix: do not try to create legend for non loaded classified layer

- Makefile
- pyproject.toml
- umap/asgi.py
- umap/settings/base.py
> Allow to run umap with asgi

- umap/static/umap/js/modules/data/layer.js
This was added by the browser I think, but let's be explicit, just in case.
cf https://github.com/umap-project/umap/pull/2224#pullrequestreview-2382243375
> chore: explicitely add geojson extension when downloading a layer

- umap/static/umap/js/modules/rendering/ui.js
- umap/static/umap/js/modules/ui/panel.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
And only this panel.
This was creating a weird bug, steps to reproduce:
- create a marker
- shift-click on the marker to edit the layer (so without explicitly closing the panel)
- try to type the layer name: the panel would close
This is also because currently the schema and render() are too dump, and when any `name` is changed then the `data` reflow is called, while it should not when editing the datalayer name.
We want to:
- have more targeted schema
- have more specific reflow in render
But that's for other PRs!
> fix: always unset editedFeature on editPanel close

- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/global.js
- umap/static/umap/js/modules/permissions.js
- umap/static/umap/js/modules/saving.js
- umap/static/umap/js/umap.controls.js
- umap/static/umap/js/umap.js
- umap/static/umap/map.css
- umap/tests/integration/test_edit_datalayer.py
- umap/tests/integration/test_optimistic_merge.py
- umap/tests/integration/test_save.py
The last refactor of the save process (0fdb70ce669838f9fd66eb5de570ffde78e3653d) has introduced a bug: the save flow was not more stopped when a layer fail to save. This ends with a broken UI, as the map is not dirty anymore, so the save button is not active anymore, while at least one layer still needs to be saved.
Save can fail in two scenarios:
- there is a conflict (status 412)
- the server is down or as an issue (eg. disk is full)
I tried a more modest scenario (listening for status in map.save and recallign the map save after a conflict), but this ended with calling map.save uselessly even more.
So I decided to try this refactor, which also totally remove the useless map.save we were sending at each save until now.
> chore: introduce SaveManager class

- umap/static/umap/js/modules/rendering/template.js
- umap/tests/integration/test_view_marker.py
The default popup template expects a `name` key, so let's populate it.
> fix: honour custom labelKey in default popup template

- umap/static/umap/js/modules/rules.js
- umap/static/umap/js/modules/slideshow.js
- umap/static/umap/js/modules/umap.js
Side note (for another PR I'd say): this usually occurs on a non saved map, but in case the map already exist and is in sync mode, should we sync each property (safer but one call per property) or the whole properties object (lighter, but may override unwanted things in remote, and currently there is no method to do so).
> fix: honour `rules` and `slideshow` when importing a umap file

- package.json
Given that we need to support ES6 modules, better to write it down explicitely.
Current audience coverage is unchanged: 88.3 %
See https://browsersl.ist/#q=%22browserslist%22%3A+%5B%0A++%22defaults+and+fully+supports+es6-module%22%0A%5D vs. https://browsersl.ist/#q=%22browserslist%22%3A+%5B%0A++%22%3E+0.5%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+dead%2C+not+op_mini+all%22%0A%5D
> chore: update browserslist to be more explicit

- umap/static/umap/js/modules/rendering/popup.js
- umap/static/umap/js/modules/rendering/template.js
- make sure we have correct `this` in callback
- do not call anymatePan if icon is not added to map (because clusterized)
> fix: do not fail when navigating with popup arrows in cluster mode

- umap/static/umap/js/modules/importers/overpass.js
In other words: fill in the "tags" input with the latest typed expression.
Otherwise, when making tries with overpass imports, one have to type it again and again (it's available through the autocomplete, though, but it's not obvious and it's less friendly IMHO).
> feat: make expression persistent in the overpass importer

- docs/config/settings.md
- umap/settings/base.py
- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/rendering/template.js
- umap/static/umap/js/modules/rendering/ui.js
- umap/static/umap/js/modules/tableeditor.js
- umap/static/umap/js/modules/umap.js
- umap/static/umap/js/modules/utils.js
- umap/tests/integration/test_browser.py
- umap/views.py
fix #2289
Let's add "nom" in OSM France and ANCT instances, then, to make users experience smoother (a lot of imported data contains a "nom" column, and no "name" nor "title").
> feat: allow to configure the default label keys per instance

- umap/static/umap/js/modules/rendering/map.js
Changing map options at this stage is too late.
cf #2340
> fix: disable for real dragging the map on mobile when scrollWheelZoom is false

- umap/management/commands/empty_trash.py
- do not try to print map.id after delete (it's None)
- rely on date instead of minutes/microseconds
> chore: review empty_trash command

- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/importer.js
- umap/static/umap/js/modules/umap.js
We basically make the all import chain return the results as promise, so the importer can act at the end of the process and:
- zoom only to the imported data (in case the layer already as some)
- display a counter of imported data when import is successfull
- display an alert when nothing has been imported
cf #564
> feat: refactor importer feedback

- umap/static/umap/js/umap.forms.js
UMap will look into the schema for default values, but untill now FormBuilder wasn't.
This fix is not the real fix we want, but let's make this last until then.
The real fix is to refactor schema and make obj.properties a Proxy object that will then be consumed by FormBuilder as it is now.
> fix: teach FormBuilder where to look for default values

- umap/static/umap/js/modules/rendering/ui.js
- umap/static/umap/map.css
- umap/static/umap/vars.css
fix #2351
The actual zIndex of a marker is computed by Leaflet, not set in CSS.
> fix: bring marker to front on highlight

- umap/static/umap/css/form.css
- umap/static/umap/js/modules/umap.js
- umap/static/umap/js/umap.forms.js
- umap/tests/integration/test_edit_datalayer.py
fix #1995
https://github.com/user-attachments/assets/b16d7d1b-eee1-4da2-93b9-2aac127051ba
> feat: allow to edit datalayer name in datalayers list

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/icon.js
- umap/static/umap/js/modules/rendering/ui.js
- umap/static/umap/js/modules/umap.js
Otherwise, when the marker is redrawn by Leaflet itself, it will lose the status (the class we added manually will not be added by Leaflet).
Eg. if we click on a marker on the map border, this will move the map to make the marker popup fit the screen, and thus this will redraw the marker icon, which will then lose the "active" flag class.
> fix: store the "active" status of a feature

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/popup.js
- umap/static/umap/js/modules/rendering/template.js
- umap/static/umap/js/modules/schema.js
- umap/static/umap/js/modules/utils.js
When the data contain a `wikipedia` attribute, like used in OSM data (see https://wiki.openstreetmap.org/wiki/Key:wikipedia), this template will fetch the image and an extract for the given page.
fix #661
> feat: experimental popup template for wikipedia

- umap/static/umap/js/modules/data/layer.js
When asking for cancel, a layer that has not yet been saved to the server should only be erased, no need to try to restore its previous state.
> fix: do not try to restore a newly created layer on reset

- umap/static/umap/js/modules/caption.js
This could have been a four letters fix (adding class "text"), but I've seen that `Caption` was still using `DomUtil` instead of `WithTemplate`, so I made this little effort more…
> fix: honour carriage returns in layer description (in caption panel)

- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/importer.js
- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/static/umap/js/modules/umap.js
- umap/tests/integration/test_websocket_sync.py
Here are the main fixes:
- mark a synched datalayer as loaded (so the peer does not try to get data from the server)
- do not mark synched datalayers as dirty
- properly consume the lastKnownHLC, so to get an accurate list of operations
fix #2219
> Fix duplicated content during sync

- umap/static/umap/js/modules/umap.js
Some maps have dozens, even hundreds of layers
> fix: do not load all datalayers at once

- umap/static/umap/js/modules/ui/bar.js
- umap/static/umap/js/modules/umap.js
fix #2265
Let's reactivate when we have a proper undo-redo (cf #1107)
> fix(sync): deactivate cancel and hide button when sync is active

- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/websocket.js
We now set the "closeRequested" on the receiver itself, otherwise there is a race condition between the reconnect (which create a new transport) and the onclose checking closeRequest on an old transport.
> fix(sync): do not try to reconnect after end edit

- umap/tests/test_datalayer.py
- umap/tests/test_datalayer_views.py
- umap/views.py
> fix: update map.modified_at when saving a datalayer

- umap/static/umap/js/modules/caption.js
- umap/static/umap/map.css
- umap/tests/integration/test_caption.py
- umap/views.py
> feat: display map's "created at" and "modified at" in the caption

- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/tests/base.py
- umap/tests/integration/test_websocket_sync.py
fix #2268
There is a tricky choice to do: the delete actually occurs in two
times, first the datalayer is hidden from the UI and set as "deleted"
(this can then be undone) then at next "save" it will totally removed.
When syncing, given we removed the "reset/undo" feature for now, and
because it was simpler, I decide to do both step in once.
When working on a proper "undo/redo", we may challenge this choice
again.
> fix(sync): handle sync of datalayer delete

- umap/static/umap/js/modules/browser.js
fix #2430
Not exactly sure how to make this DRY. What we want is to mark the layer visibility as "controlled by user" as soon as they click on a show/hide/showAll/hideAll button, so we do not try to infer the visibility from the from/toZoom settings.
> fix: keep layer visibility after clicking on toggle all

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/layers/classified.js
- umap/static/umap/js/modules/tableeditor.js
fix #2446 
A bunch of small commits, but real fixes are: https://github.com/umap-project/umap/commit/29d70552dd1f68eef4ba9929c0db17dd785a73e9 and https://github.com/umap-project/umap/commit/d5efe6b8e260863527b9a6a15fb9059d570f2559 and https://github.com/umap-project/umap/commit/8f2bbc6765010c001d12531ab1d4aabca46a177f
> Fix categorized layers colors palette not updating

- umap/static/umap/js/modules/data/layer.js
In some situation, we do not want the same sortKey for each layer.
> feat: allow to define sortKey at layer level

- charts/umap/templates/deployment.yaml
Related to helm Charts:
Currently the reference to secret is done by
```          
envFrom:
- secretRef:
name: {{ .Release.Name }}-env
```
[Link](https://github.com/umap-project/umap/blob/master/charts/umap/templates/deployment.yaml#L67C1-L69C44)
but secret object is created like this:
```
metadata:
name: {{ include "umap.fullname" . }}-env
```
[Link](https://github.com/umap-project/umap/blob/master/charts/umap/templates/secret-env.yaml#L4C3-L4C4)
Works as long as no Sub-Chart feature is used, when individual configuration is stored within a git repo.
Then the subchart name is added to fullname. (And I think if custom fullName is set)
To be safe, `{{ include "umap.fullname" . }}` is correct. 
Should be no breaking change, when it is working at the moment. (Because then both return same …
> fix(helm): reference secret-env by fullname instead release-name

- umap/static/umap/js/modules/form/fields.js
- umap/static/umap/js/modules/utils.js
- umap/tests/integration/test_import.py
- umap/tests/integration/test_optimistic_merge.py
- umap/tests/integration/test_save.py
- umap/tests/integration/test_tableeditor.py
- umap/tests/integration/test_websocket_sync.py
fix #2415
I'm a bit afraid this will add more hiccup to the playwright tests, tough :(
> feat(forms): add a debounce for Input and Textarea fields

- docs/config/settings.md
- umap/context_processors.py
- umap/settings/base.py
- umap/templates/auth/user_detail.html
- umap/templates/auth/user_form.html
- umap/templates/auth/user_stars.html
- umap/templates/base.html
- umap/templates/registration/login.html
- umap/templates/umap/about.html
- umap/templates/umap/map_detail.html
- umap/templates/umap/password_change.html
- umap/templates/umap/password_change_done.html
- umap/templates/umap/search.html
- umap/templates/umap/team_confirm_delete.html
- umap/templates/umap/team_detail.html
- umap/templates/umap/team_form.html
- umap/templates/umap/user_dashboard.html
- umap/templates/umap/user_teams.html
- umap/tests/integration/test_basics.py
This is not the same as the short `SITE_NAME` which is displayed as the title of the (home)page for instance.
The plan is to set `SITE_DESCRIPTION` as `uMap OpenStreetMap` for the OSM instance and `uMap agents publics` for the ANCT one.
> a11y: include site description within page titles

- umap/static/umap/js/modules/rendering/layers/cluster.js
Eg. to reproduce: a map with a limitBounds that makes uMap immediately zoom to fit the bbox.
> fix: catch cluster error at zoom in certain situation

- umap/static/umap/js/components/alerts/alert.js
Otherwise, when an infinite alert replace an alert with a finite duration, this first alert timeout will close the second alert.
> fix: clear previous alert timeout when opening a new alert

- umap/static/umap/js/modules/data/layer.js
This occurs when a remote data returns an invalid geojson.
> fix: do not try to backup an undefined geojson

- umap/static/umap/js/modules/rendering/ui.js
When moving a path, this will put a once time listener on "moveend". If we delete this feature, and move the map, we should not execute the event callback.
A better fix would be to cancel the event listener on delete, but that is much more work given how we deal with Leaflet events right now.
> fix: error after deleting a path that was previously moved

- docs/deploy/asgi.md
- docs/deploy/nginx.md
- mkdocs.yml
This is just about ASGI, not the websockets and the sync itself.
We may merge it, or just keep it and amend it until we have the sync official.
> chore: add very minimal documentation for deploying uMap with ASGI

- umap/static/umap/js/modules/rendering/ui.js
- umap/tests/integration/test_websocket_sync.py
This is more unified between markers and paths, and it allows paths to be synced as soon as they have been drawn (instead of when closing the edit panel, which created a race condition when changing its properties that were then synced to other while the feature itself was not).
> chore: use editable-edited event to sync changes

- umap/static/umap/js/modules/form/builder.js
- umap/static/umap/js/modules/form/fields.js
- umap/static/umap/js/modules/schema.js
- umap/tests/integration/test_edit_map.py
- umap/tests/integration/test_view_marker.py
Broken since c27e675152b095a3a77c10a9e27d87a90a79ca85
> Fix broken showLabel=null (on hover)

- umap/static/umap/js/modules/rendering/ui.js
Until now, it was displayed on the path (line or polygon) "center". So when zoomed in, if the center is not on the screen, the tooltip will not be visible.
> feat: make the tooltip sticky in hover mode for paths

- umap/static/umap/js/umap.controls.js
- umap/static/umap/map.css
Before:
After:
(Size unchanged on mobile)
cf #673
> feat: make vertex icons bigger (and round)

- umap/models.py
- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/rendering/layers/classified.js
- umap/static/umap/js/modules/saving.js
- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/static/umap/js/modules/umap.js
- umap/sync/app.py
- umap/sync/payloads.py
- umap/tests/integration/test_websocket_sync.py
When a peer save the map, other peers in dirty state should not need to save the map anymore.
That implementation uses the lastKnownHLC as a reference, but it changes all dirty states at once. Another impementation could be to have each object sync its dirty state, but in this case we do not have a HLC per object as reference, and it also creates more messages.
ping @almet if you're around and wanna have a fresh look. :)
> chore: sync save state

- umap/static/umap/js/modules/sync/engine.js
Otherwise, if the token request fail, the process will be stopped and we will never try to reconnect.
> fix(sync): try to reconnect after network error when getting token

- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/sync/websocket.js
Websocket has now a "connect" method, which is a promise, that yields "onconnect", so the engine can wait for it before proceding.
> fix(sync): wait for websocket full connection

- umap/static/umap/js/modules/sync/updaters.js
- umap/tests/integration/test_websocket_sync.py
That fix does not really fix the original issue, but it makes it impactless, and I think it's safer anyway to have upsert idempotent.
The pattern to reproduce is:
- peer A create a synced map, add a datalayer, save it
- peer B loads the map, click on edit
- at this time, peer B have twice the datalayer data, once from the server AND once from the sync
So a better fix would be to make that peer B send a meaningfull HLC to peer A I guess.
For this we may save the last HLC is the map properties, or maybe try to merge the "reference_version" and the HLC.
> fix(sync): make datalayer upsert idempotent

- umap/static/umap/js/modules/ui/base.js
Broken since 70f87d863606576ee4e363cf24f6ddf8d1b3242b
fix #2539
Before:
After:
> fix: measure/drawing tooltip was misplaced

- umap/views.py
Seems that in some situation it is not defined.
We have this error in Sentry, but I'm not able to reproduce myself to get a better context:
https://umap.sentry.io/issues/6351694806/?alert_rule_id=14960738&alert_timestamp=1741028858715&alert_type=email&environment=osmfr&notification_uuid=2c437997-d14d-4e0f-a62f-55bd19739ad2&project=4506656504020992&referrer=alert_email
> fix: be defensive when getting the backend name from the session

- umap/templates/umap/map_fragment.html
One of the side-effects is to make the content of the map un-focusable but we also loose the ability to interact with the map itself.
> a11y: turn embeded maps into inert elements

- umap/static/umap/js/modules/data/layer.js
The problem we've tried to fix is, during sync:
- peer A is editing a feature
- peer B changes the datalayer of this feature
- edit panel is closed for peer A
> fix: use real redraw for datalayer, instead of hide/show

- umap/static/umap/js/modules/umap.js
- umap/tests/fixtures/test_upload_data_with_iconurl.umap
- umap/tests/integration/test_import.py
This will only cover the cases where the icon is set at the map or at the layer level, not the one of the marker itself.
cf #2552
> fix: import iconUrl as absolute when possible

- umap/static/umap/map.css
The button is already on the edit bar.
Would be nicer to have a css transition (like for the bar itself), but at least with this change it is not duplicated.
> fixup: hide home button in edit mode

- umap/models.py
Some geojson have been removed by mistake time ago (cf #1003), when someone tries to load a map referencing them, it was until recently just showing an error message, but since recently we try to get the metadata from it, and this will crash.
> fix: do not fail when trying to read metadata of a missing geojson

- umap/static/umap/base.css
- umap/static/umap/content.css
- umap/static/umap/map.css
- umap/static/umap/vars.css
- umap/templates/auth/user_detail.html
- umap/templates/auth/user_stars.html
- umap/templates/umap/content.html
- umap/templates/umap/home.html
- umap/templates/umap/map_list.html
- umap/templates/umap/search.html
- umap/templates/umap/team_detail.html
> feat: display maps list as a grid now

- umap/static/umap/js/modules/help.js
- umap/static/umap/js/modules/ui/bar.js
- umap/static/umap/js/modules/umap.js
- umap/static/umap/js/modules/utils.js
I've reworked a bit the shortcut handling, as it was only dealing with ctrl/meta only ones (no shift).
> feat: add keyboard shortcut for redo (ctrl+shift+z)

- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/data/layer.js
- umap/tests/integration/test_browser.py
- umap/tests/integration/test_edit_datalayer.py
- umap/tests/integration/test_owned_map.py
- umap/tests/integration/test_websocket_sync.py
Now that we have granular undo, I'd say we can simplify the delete process.
> Remove confirm delete for features and datalayers

- umap/static/umap/js/modules/utils.js
Do not call toString on a null value
> fix: fix categorized layer crashing with null value

- umap/autocomplete.py
- umap/tests/test_views.py
Basically, when the search is "joe" we first try to search for an exact account named "joe", and fallback to normal flow when nothing matches.
fix #2591
> fix: give priority to small usernames on autocomplete

- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/umap.js
> feat: use Last-Modified header from remote data when available

- umap/static/umap/js/modules/form/fields.js
> fix: display back help button in switch fields

- umap/static/umap/js/modules/data/layer.js
cf #2625
This happens while drawing a line or polygon and then hitting escape while the path is not yet valid.
> fix: do not try to remove a feature not yet added

- .github/workflows/release-helm.yml
- charts/umap/templates/deployment.yaml
- charts/umap/templates/secret-config.yaml
- charts/umap/templates/secret-env.yaml
- charts/umap/values.yaml
- env vars and config files can be loaded from existing secrets
- chart is deployed on a helm repository
to make the helm repository work with github pages, create an empty orphaned branch called gh-pages, and under settings>pages>source select deploy from branch and use gh-pages
> Adapt chart to match La Suite's expectations

- umap/settings/base.py
Allow to manage djangos CSRF_TRUSTED_ORIGINS by environment variables.
Closes #2655
> feat: pass CSRF_TRUSTED_ORIGINS env to settings

- umap/static/umap/js/modules/data/layer.js
This could occur when server is down or there is no network.
> fix: show an error message if saving layer failed

- umap/models.py
- umap/static/umap/js/modules/browser.js
- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/facets.js
- umap/static/umap/js/modules/form/fields.js
- umap/static/umap/js/modules/importer.js
- umap/static/umap/js/modules/managers.js
- umap/static/umap/js/modules/permissions.js
- umap/static/umap/js/modules/rendering/map.js
- umap/static/umap/js/modules/schema.js
- umap/static/umap/js/modules/share.js
- umap/static/umap/js/modules/slideshow.js
- umap/static/umap/js/modules/sync/engine.js
- umap/static/umap/js/modules/ui/bar.js
- umap/static/umap/js/modules/umap.js
- umap/tests/base.py
- umap/tests/integration/test_optimistic_merge.py
This also:
- introduces a new DataLayerManager
- removes the _umap_options coming from the geojson form the server
- removes all backup related functions (now we have undo/redo)
fix #2674
> fix: allow to save/undo/sync drag'n'drop of datalayers

- umap/static/umap/js/modules/caption.js
- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/data/layer.js
- umap/static/umap/js/modules/importer.js
- umap/static/umap/js/modules/permissions.js
- umap/static/umap/js/modules/rendering/icon.js
- umap/static/umap/js/modules/rendering/layers/base.js
- umap/static/umap/js/modules/rendering/layers/classified.js
- umap/static/umap/js/modules/rendering/layers/cluster.js
- umap/static/umap/js/modules/rendering/layers/heat.js
- umap/static/umap/js/modules/sync/updaters.js
- umap/static/umap/js/modules/ui/bar.js
- umap/static/umap/js/modules/umap.js
This aligns with what we do on other uMap objects. `options` should be only used in the Leaflet world.
> chore: switch from DataLayer.options to DataLayer.properties

- umap/static/umap/js/modules/rendering/layers/cluster.js
The parent `_moveChild` method will call removeLayer then addLayer again (to add it to the correct cluster), but this will then deactivate further event listener, including our dragEnd listener, which is the one responsible for adding the change in the save/undo/sync queue.
One other option would be to make that our dragEnd call comes before their, but it's harder to do, as it is markercluster `addLayer` itself to decide in which order those listener are added, and thus called.
fix #2749
> fix: fix dragged marker not savable when in cluster layer

- docs/maintenance/management_commands.md
- mkdocs.yml
- umap/management/commands/purge_old_versions.py
- umap/storage/fs.py
- umap/tests/test_purge_old_versions.py
Old versions are usually deleted on save of a datalayer, but we still keep UMAP_KEEP_VERSION. Let's say after some time even those versions could be deleted, to save some space.
> feat: add management command to purge old versions

- umap/static/umap/map.css
> Fix img center rules caption

- umap/static/umap/js/modules/ui/contextmenu.js
Sometimes we have no button but just a tags (eg. the menu in the top edit bar)
> fix: focus whatever first button or a tag in a contextmenu

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/layers/cluster.js
Our naive algorithm complexity is related to the number of clusters, so let's not compute clusters outside of the map bounds.
> fix: only compute clusters for visible features

- umap/static/umap/js/modules/rendering/ui.js
> fix: allow back to drag a marker while in a cluster layer

- umap/static/umap/js/modules/rendering/map.js
Otherwise, when trying to set a custom tilelayer, this will not be reflected in the map unless save and reload.
> fix: update map options from umap properties before computing tilelayer

- umap/static/umap/js/modules/data/layer.js
When a MultiPoint has only one member, we import it as a Point, but until now we do not change the type, which then creates an invalid MultiPoint (with only one "coordinates" member).
fix #2906
> fix: properly convert MultiPoint to Point

- umap/static/umap/js/modules/managers.js
- umap/static/umap/js/modules/umap.js
Our first algo to create features id has created a lot of duplicate, so we need to recompute them, which can take quite a lot of CPU when there are a lot of features. So let's warn the editor about this so they can save the layer again, resetting the ids.
cf #2813
> chore: make datalayer dirty when duplicate id has been found

- umap/static/umap/js/modules/formatter.js
- umap/tests/integration/test_export_map.py
This allow to keep the complex geometries (polygon, polyline), and may also allow to reimport the data in Grist so to edit them there and add them in remote data.
> feat: add export in CSV with WKT geometry

- umap/static/umap/js/modules/data/features.js
- umap/static/umap/js/modules/rendering/ui.js
This happens for example when saving a layer while it has some features filtered.
> fix: do no try to redraw a feature not on the map

- umap/static/umap/js/modules/domutils.js
- umap/static/umap/js/modules/rendering/layers/classified.js
We want to match the feature color on the map, as much as possible (this will fit for light tiles, but not for dark ones).
fix #2907
> fix: add opacity to classified layer legend color
