umap-project/umap

.gitignore
Ignore unwanted files Mac OS, Linux and Python
=> Improved gitignore with gitignore.io

umap/context_processors.py, umap/settings/base.py, umap/settings/local.py.sample, umap/templates/registration/login.html, umap/templates/umap/navigation.html, umap/templates/umap/password_change.html, umap/templates/umap/password_change_done.html, umap/urls.py
This pull request should enable login via username / password, if configured in the settings to allow this kind of method.
TODO:
=> Authentication: login via username / password

umap/static/umap/nav.css, umap/static/umap/umap.css, umap/templates/base.html, umap/templates/umap/content.html, umap/templates/umap/navigation.html
=> Switch to Flexbox for main navigation

umap/templates/auth/user_detail.html
Just created my account on umap.osm.org and I found this untranslated.
=> Mark a string for translation

docs/ubuntu.md
Added missing dependency packages
Added missing ownership to deployment directories
=> Updated ubuntu installation doc

README.md
From the context, I think it was implied that OpenStreetMap is *improved* by community adoption, rather than being 'cured' of some 'sickness' :-)
=> Change 'cured' to 'improved'

docs/ubuntu.md
I had to add a config for /static and /uploads folder in nginx when I set DEBUG = False
=> Update ubuntu from scratch doc

umap/static/umap/base.css, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.popup.js, umap/static/umap/map.css
=> Adapt iframe and image width when in right panel

docs/install.md
=> Fix typos on Install docs

umap/static/umap/base.css, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/static/umap/js/umap.popup.js, umap/static/umap/map.css
=> Improve popup and panel layout

docs/contributing.md, docs/index.md, docs/install.md, docs/install_windows.md
=> add Windows install info and minor typos

.travis.yml, requirements-dev.txt, requirements.txt, umap/fields.py, umap/forms.py, umap/middleware.py, umap/models.py, umap/settings/__init__.py, umap/settings/base.py, umap/tests/base.py, umap/tests/settings.py, umap/urls.py, umap/utils.py, umap/views.py
Bloqued by https://github.com/peopledoc/django-agnocomplete/issues/119
=> First attempt to upgrade to Django 3.X

docs/install.md
Signed-Off-By: Matt Cengia <mattcen@mattcen.com>
=> Update table names in Search/Optimisation docs

setup.cfg
=> Declare incompatibility with Django 4

umap/static/umap/js/umap.core.js
Thanks @andrew-black512
Fixes #1009
=> Typo: missing `h` in character’s string

setup.cfg
Fixes #963, thanks @kkuczkowska
=> Allow versions of Django >= 4.1

SECURITY.md
=> Create SECURITY.md to report security issues

umap/static/umap/js/umap.js
We removed it by mistake in 25ab9f943c59c15eee0eb3551008dfbd692a3479
cf https://github.com/domoritz/leaflet-locatecontrol#possible-options
=> Use flyTo option in locate if map settings aks for it

.prettierrc.yaml, Makefile, package-lock.json, package.json, umap/static/umap/js/umap.autocomplete.js, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.icon.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/static/umap/js/umap.permissions.js, umap/static/umap/js/umap.popup.js, umap/static/umap/js/umap.slideshow.js, umap/static/umap/js/umap.tableeditor.js, umap/static/umap/js/umap.ui.js, umap/static/umap/js/umap.xhr.js
Refs https://github.com/umap-project/umap/pull/1081
=> Apply PrettierJS to the whole codebase

Makefile, package-lock.json, package.json, umap/static/umap/js/umap.autocomplete.js, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/static/umap/js/umap.permissions.js, umap/static/umap/js/umap.popup.js, umap/static/umap/js/umap.slideshow.js, umap/static/umap/js/umap.tableeditor.js, umap/static/umap/js/umap.xhr.js
[Arrow functions](https://caniuse.com/arrow-functions) will exclude IE11 but global usage is at  96.96%
=> Install and apply Lebab for JS arrows’ conversions

umap/static/umap/map.css
Fix #887 as suggested by @esteban-em
=> Max width for the help box (on small screens)

umap/tests/conftest.py, umap/tests/test_views.py, umap/urls.py, umap/views.py
Will be useful to feed munin for instance.
=> Add a very basic `/stats/` JSON view

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js
=> Also expose direct map URL in the export panel

Makefile, umap/static/umap/js/umap.autocomplete.js, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.icon.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/static/umap/js/umap.permissions.js, umap/static/umap/js/umap.popup.js, umap/static/umap/js/umap.slideshow.js, umap/static/umap/js/umap.tableeditor.js, umap/static/umap/js/umap.ui.js, umap/static/umap/js/umap.xhr.js, umap/templates/umap/locale.js
As far as I understand, it default to `let` in these cases because the tool cannot figure out if a `const` is possible. It has to be checked manually:
```
./node_modules/lebab/bin/index.js --replace "umap/static/umap/js/*.js" --transform let
umap/static/umap/js/umap.xhr.js:
228:  warning  Unable to transform var  (let)
umap/static/umap/js/umap.ui.js:
83:  warning  Unable to transform var  (let)
umap/static/umap/js/umap.slideshow.js:
15:  warning  Unable to transform var  (let)
83:  warning  Unable to transform var  (let)
umap/static/umap/js/umap.popup.js:
100:  warning  Unable to transform var  (let)
umap/static/umap/js/umap.permissions.js:
14:  warning  Unable to transform var  (let)
umap/static/umap/js/umap.layer.js:
195:  warning  Unable to transform var  (let)
436:  warning  Unable to …
```
=> Apply Lebab for let/const conversions

Makefile, package-lock.json, package.json, umap/static/umap/js/umap.core.js, umap/static/umap/test/Util.js, umap/static/umap/test/index.html, umap/templates/umap/js.html
There are a lot of [complex](https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html) [potential](https://portswigger.net/web-security/cross-site-scripting/cheat-sheet) use cases that were not covered.
It adds an extra 7.8Kb once minified+gzipped.
=> Use DOMPurify to escape malicious input from user

umap/context_processors.py, umap/templates/umap/about_summary.html, umap/templates/umap/content.html, umap/templates/umap/home.html, umap/templates/umap/navigation.html, umap/tests/test_views.py, umap/views.py
=> Banner + no create buttons when in read only mode

umap/static/umap/js/umap.js
Fix #420, hopefully the fuzzy translations will be updated!
=> Better zoom set/modified wording

umap/static/umap/map.css
See https://umap.openstreetmap.fr/en/map/example01_923828#5/53.606/9.009 for example
=> Fix width of columns in popups and tables

.github/FUNDING.yml
Hopefully, that's the way to go :p
=> Add Liberapay funding

umap/static/umap/map.css
=> Avoid popup content to extend beyond the space allowed

umap/static/umap/js/umap.js, umap/static/umap/nav.css, umap/templates/umap/content_footer.html, umap/views.py
=> Display the current version + link to changelog

umap/templates/umap/search.html, umap/views.py
=> Display the number of maps on search results page

umap/static/umap/map.css
Refs https://github.com/umap-project/umap/pull/1149
Refs https://github.com/umap-project/umap/pull/1143
There are still issues with resize+(max-)height combination, to be addressed in a future release.
=> Back to max-height only for datalayers

umap/tests/test_views.py, umap/views.py
=> Expose version in /stats/ endpoint

umap/management/commands/anonymous_edit_url.py
=> Allow to set the lang while generating an anonymous_edit_url

umap/static/umap/js/umap.controls.js, umap/static/umap/map.css, umap/static/umap/test/Feature.js
fix #692
(Pictos are clearly unaligned! This needs to be fixed, but it's outside this PR)
=> Add "delete" link in data browser

umap/static/umap/js/umap.core.js, umap/static/umap/test/DataLayer.js
fix #353
+ a bit of prettier noise, sorry
=> More natural sort of features

package.json, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.features.js, umap/static/umap/test/Marker.js
cf https://forum.openstreetmap.fr/t/impossible-de-charger-la-carte-carte-acteurs-naturels-batiment/15607/7
=> Be more strict when coordinates are set manually

umap/static/umap/js/umap.controls.js, umap/static/umap/test/Controls.js
But the scollWheelZoom that is forced to true.
fix #390
=> Fullscreen link should reflect the user choices

umap/static/umap/js/umap.core.js, umap/static/umap/test/Util.js
=> Allow to sort reverse

umap/static/umap/js/umap.xhr.js
=> Handle CORS errors with an explicit message

umap/settings/base.py, umap/settings/local.py.sample, umap/views.py
Useful for https://github.com/umap-project/umap-dsfr
=> Add a setting for the number of maps per search

Dockerfile
More friendly then to run umap commands inside the container or even `docker compose run app umap xxx`
=> Add umap command in Docker PATH

umap/static/umap/js/umap.core.js, umap/static/umap/test/Util.js
=> Do not ignore punctuation when sorting features

umap/static/umap/js/umap.permissions.js
cf https://forum.openstreetmap.fr/t/apres-enregistrement-dune-carte-les-permissions-ne-sont-pas-presentes/15995
=> Fix permissions panel empty at first save

umap/static/umap/map.css
=> We do not want horizontal overflow/scroll bar in popups

package.json, umap/static/umap/js/umap.layer.js
Changelog:
https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md
Sounds safe for us. Tested localy. Tests pass. Inch Allah.
=> Bump Leaflet to 1.9.4

umap/static/umap/map.css
=> Better fit iframe in popup

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.ui.js
Otherwise, wheel will zoom the map even when sent on a panel or control.
=> Switch from mousewheel to wheel, as Leaflet did

umap/models.py, umap/templates/umap/map_table.html, umap/tests/test_views.py
=> Display share status in dashboard

umap/static/umap/js/umap.core.js
=> Update labelKey help text

umap/static/umap/js/umap.core.js, umap/static/umap/test/Util.js
=> Allow to use arobase in variables

umap/static/umap/js/umap.core.js, umap/static/umap/test/Util.js
May break some undocumented cases…
cf #139 #676
=> Be more liberal in what chars a variable can contain

umap/static/umap/js/umap.features.js
=> Do not modify tooltipAnchor inplace, as it's shared by all markers

umap/static/umap/js/umap.xhr.js
=> Add target URL in CORS error message

umap/static/umap/js/umap.controls.js
fix #1225
Did not find a way to have uni test for this, given we are using a Blob with a createObjectURL…
=> Use proper GPX mimetype

umap/static/umap/base.css
=> Fix misplaced icons

package.json, scripts/vendorsjs.sh
=> Use maintained fork of togeojson

umap/static/umap/js/umap.features.js
=> Do not try to compute geom based property before we have a geom

umap/static/umap/js/umap.controls.js
=> Do not close panel when switching tilelayer

umap/static/umap/js/umap.layer.js
=> Make sure filters are called before actually displaying a feature on the map

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.js, umap/static/umap/map.css, umap/static/umap/test/DataLayer.js
=> Allow to control facet labels

umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.forms.js
`undefined` can end with unwanted situations, so let's try to avoid that.
[Screencast from 2023-08-09 09-09-47.webm](https://github.com/umap-project/umap/assets/146023/c5d3c40b-4f46-4dfd-b187-57c733c28a09)
=> Explicitely use map default when dynamic var is unset

umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.layer.js, umap/static/umap/test/DataLayer.js
=> Make fromZoom and toZoom options available for all layers

umap/static/umap/js/umap.js
=> Fix bug where minimap would not be displayed on load

umap/static/umap/js/umap.controls.js
=> When map has max bounds, use those bounds for limiting search

umap/static/umap/js/umap.layer.js, umap/static/umap/test/DataLayer.js, umap/static/umap/test/_pre.js
=> Fix datalayers being shown on zoom even if displayOnLoad is false

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js, umap/static/umap/test/Map.Export.js, umap/static/umap/test/Polyline.js, umap/static/umap/test/index.html
=> Make sure we load all data before downloading it

umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js
May worth a pair review, to challenge the problem and the solution :)
=> Fix datalayers not sending "dataloaded" event when min/maxZoom is set and map is loaded outside those values

umap/static/umap/js/umap.features.js
=> Put focus on name when opening feature edit panel

umap/static/umap/base.css, umap/static/umap/js/umap.ui.js
fix #870
Before:
[Screencast from 2023-08-30 12-38-37.webm](https://github.com/umap-project/umap/assets/146023/70530596-c458-48f8-8ac6-b4063b7c3cec)
After:
[Screencast from 2023-08-30 12-37-47.webm](https://github.com/umap-project/umap/assets/146023/b2aa1b47-ee6d-4518-aab9-462a6db9a8f2)
=> Better distinguish panel behaviour in portrait vs landscape modes

umap/static/umap/base.css, umap/static/umap/js/umap.forms.js
- change links to buttons
- make that "advanced raw field" can be toggled
- add a search field to filter icons from their name
- restore icon preview that has disappeared recently
fix #1302
=> Enhance icon selector form

Makefile, pyproject.toml, pytest.ini, umap/tests/conftest.py, umap/tests/integration/__init__.py, umap/tests/integration/test_basics.py
More as a working base for a discussion on the topic.
=> Setup to create integration tests with Playwright

umap/static/umap/js/umap.controls.js
=> Add a `powered by uMap` footer

umap/static/umap/js/umap.js
Fix #1312
Is there something else, that needs to be added? Seems to work locally.
=> Add outlinkTarget to default interactionProperties

umap/static/umap/js/umap.features.js, umap/static/umap/test/Map.js
Otherwise it will break when trying to access it in FormBuilder
=> Remove dot in property name

docs/settings.md
See https://github.com/umap-project/umap/pull/1322#issuecomment-1726300269
=> Better documentation for the SECRET_KEY setting

umap/tests/test_views.py, umap/views.py
=> Fix map displayed more than once in user dashboard when multiple editors

umap/models.py, umap/tests/test_datalayer.py
We'll not consume them.
fix #1317
=> Prune old .gz when saving a datalayer

umap/static/umap/js/umap.browser.js, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/static/umap/test/index.html, umap/templates/umap/js.html, umap/tests/base.py, umap/tests/integration/test_browser.py
This PR is quite big because I've refactored how databrowser works in the same time…
fix #1338
=> Allow to restrict data browser items to current map view

umap/views.py
=> Make sure SHORT_SITE_URL is defined to expose Map.short_url

umap/static/umap/js/umap.controls.js, umap/static/umap/map.css
fix #844
[Screencast from 2023-09-27 10-28-28.webm](https://github.com/umap-project/umap/assets/146023/54a927b0-97c9-4c62-82fd-f83a89df4f17)
@davidbgk can you test with a real touch device ? I don't have one at hand, so I've just checked with Chrome device emulation…
=> Hide attribution on small screen and add a small ? to display it

umap/static/umap/base.css, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js
[Screencast from 2023-10-13 11-42-04.webm](https://github.com/umap-project/umap/assets/146023/3f13d2cc-aeb3-4204-9c4c-2be5d0a529c0)
fix #231 
Very basic. Should we yet introduce https://github.com/placemark/flat-drop-files helper ?
=> Add experimental drag and drop of file on the map container

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js, umap/tests/integration/test_export_map.py
cf https://forum.openstreetmap.fr/t/export-csv-depuis-une-umap/18290 
cf #123
fix #608
=> Add minimal CSV export

umap/static/umap/js/umap.layer.js, umap/tests/fixtures/display_on_load.umap, umap/tests/integration/test_import.py
=> Fix displayOnLoad not honoured at import

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js, umap/tests/integration/test_map.py
In view mode, we don't want the fallback that creates a new datalayer.
=> Split defaultDatalayer in defaultView/EditDatalayer

umap/static/umap/base.css, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/static/umap/js/umap.permissions.js, umap/static/umap/js/umap.popup.js, umap/static/umap/js/umap.ui.js, umap/static/umap/map.css, umap/static/umap/test/Choropleth.js, umap/static/umap/test/Controls.js, umap/static/umap/test/DataLayer.js, umap/static/umap/test/Map.js, umap/static/umap/test/_pre.js
CSS part is missing to be able to actually toggle to the `button` element. But some choices had to be discussed/made prior to that.
=> A11Y: switch from links to buttons when pertinent

docs/install.md
Just a few updates in the documentation while reading it.
=> Update installation instructions

umap/static/umap/base.css
=> Change background in pictograms list

umap/static/umap/js/umap.popup.js
=> Fix next/previous in popup footer in panel not openning next panel

umap/static/umap/base.css
=> Fix accordion arrow not displayed on Chromium

umap/views.py
This was creating a huge INNER JOIN, and is replaced by a UNION
cf https://explain.dalibo.com/plan/91af244fg9d1ec21
Also remove the conditional queryset, as now "my maps" is serverd by the dashboard page, so we can only serve public maps on this URL.
=> Fix heavy request for getting user maps

umap/views.py
Those maps can be excluded by setting their share_status=OPEN
cf #1414
=> Do not exclude DEMO and SHOWCASE maps anymore from home

umap/static/umap/map.css
fix #1418
I've also lighted a candle…
=> But back blue links in popup and small credit

docs/ubuntu.md
One more case where a "uMap devops" list/messaging could be useful…
=> Add in documentation example of filtering headers in ajax proxy conf

umap/templates/umap/map_table.html, umap/tests/test_views.py
=> Reuse the map_download view/url for the dashboard

umap/static/umap/js/umap.core.js
=> Prevent dragging a datalayer to activate drag on the map

umap/static/umap/js/umap.js
=> Fix slideshow buttons not show when facets are active

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js
cf #1436
No big deal, but still better than currently.
=> Mention more keyboard shortcuts

umap/static/umap/js/umap.js
Ref: https://forum.openstreetmap.fr/t/option-dexport-mini-carte/19223/6
=> Use map style options to style minimap bbox rectangle

umap/static/umap/js/umap.js
I see this message from time to time, but I've no details so I cannot investigate easily. Let's log the error to help.
=> Log error when loading tilelayer

SECURITY.md
Now that we have a domain name, we might want to use `security@`?
=> [docs] Update security contact information

umap/static/umap/js/umap.forms.js
Renamed `udpatePreview()` to `updatePreview()`
=> chore: fix a typo in `umap.forms.js`

umap/admin.py
=> Allow to edit pictogram categories from admin list

umap/static/umap/map.css
[Screencast from 2023-12-17 10-57-13.webm](https://github.com/umap-project/umap/assets/146023/4ec7fb05-f2ac-4e7d-8f27-779001964a9e)
=> Increase iconlayers titles on hover

umap/static/umap/base.css, umap/static/umap/img/16.svg, umap/static/umap/img/source/16.svg, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.share.js
cf #1454
(Let's make iframe textarea copiable in a later step.)
cc @jschleic :)
=> Align copy button to input in share box

umap/static/umap/js/umap.browser.js, umap/static/umap/js/umap.layer.js, umap/static/umap/map.css
=> feat(browser): add counter in datalayer headline

umap/templates/umap/map_detail.html, umap/tests/test_map_views.py, umap/tests/test_views.py, umap/urls.py, umap/views.py
Fix #162
Based on https://oembed.com/
=> Create an oEmbed endpoint for maps

umap/static/umap/map.css
=> fix(1545): fix icons for mailto and tel

umap/settings/__init__.py
=> chore: remove support for settings starting with LEAFLET_STORAGE_

umap/templates/umap/map_detail.html, umap/tests/base.py, umap/tests/integration/test_export_map.py, umap/tests/integration/test_map.py, umap/tests/test_map_views.py, umap/views.py
We could do the same for remote data sources too at some point.
=> feat: set preconnect link for tilelayer

umap/tests/integration/test_collaborative_editing.py
We needed to:
- make playwright to wait for ajax requests
- add a sleep to prevent saving two datalayer's version in the same second
=> tests: fix test_collaborative_editing_draw_markers

umap/static/umap/js/umap.layer.js
This change is already in production, but has not been commited yet…
cf #1558
=> fix: make sure we do not add geojson in options

umap/static/umap/js/umap.browser.js, umap/tests/integration/test_browser.py
=> feat: adapt browser counter to the currently displayed features

umap/tests/integration/test_owned_map.py
=> tests: remove sleep from test_owned_map

umap/static/umap/js/umap.browser.js, umap/tests/integration/test_browser.py
=> fix: use variable for color in browser if any

umap/static/umap/content.css, umap/static/umap/nav.css, umap/templates/umap/map_table.html, umap/templates/umap/navigation.html
As recommended by @Aurelie-Jallut
=> fix: improve dashboard styles

umap/static/umap/img/marker.svg, umap/static/umap/js/umap.forms.js, umap/static/umap/js/umap.icon.js, umap/static/umap/js/umap.js
=> fix: make default picto always white for now

umap/static/umap/js/umap.js, umap/tests/integration/test_star.py
Also, only display it if the user is already logged in, given we do not deal anymore with login during ajax calls.
=> fix: star control was using old post method

docs/changelog.md, docs/config/settings.md, umap/settings/base.py, umap/tests/settings.py, umap/urls.py, umap/views.py
DEFAULT_FROM_EMAIL is a Django standard setting
=> chore: replace settings.FROM_EMAIL by settings.DEFAULT_FROM_EMAIL

docker/entrypoint.sh, docs/changelog.md, umap/__init__.py
=> fix: Do not use compress anymore for Docker image

docs/deploy/docker.md
=> docs: add a note for Docker install and SECRET_KEY

umap/templates/registration/login.html, umap/templates/umap/css.html, umap/templates/umap/js.html, umap/templates/umap/map_detail.html, umap/templates/umap/map_fragment.html, umap/templates/umap/map_table.html, umap/templates/umap/user_dashboard.html, umap/tests/test_map_views.py
I'm not sure why this is not failing on master. I wonder if something is off with my machine.
=> chore: format templates

umap/management/commands/import_pictograms.py
If I wanted to import path "maki", that tried to open "maki/maki/pictogram.svg"
=> path was doubled

umap/static/umap/js/umap.js, umap/tests/integration/test_querystring.py
=> fix: zoomControl rendered twice

umap/static/umap/js/umap.share.js, umap/tests/integration/test_map_preview.py, umap/tests/integration/test_share.py
=> fix: make sure to reset feature query string parameter

umap/models.py, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js, umap/tests/integration/test_datalayer.py
=> fix: honour old_id in datalayers= query string parameter

umap/tests/integration/conftest.py
=> chore: bump the timeout for integration tests

.github/workflows/test-docs.yml, umap/tests/integration/conftest.py
so we can increase it in the CI
=> chore: allow to set playwright timeout from env var

umap/settings/base.py, umap/static/umap/js/umap.js
=> feat: add link in contextmenu to edit map in OSM

umap/static/umap/js/umap.features.js, umap/static/umap/js/umap.js, umap/tests/integration/test_map.py
=> feat: open popup when default view is set to latest

umap/static/umap/js/umap.layer.js, umap/tests/integration/test_import.py
=> feat: display a message when importer cannot find lat/lng columns

umap/static/umap/js/modules/utils.js, umap/static/umap/unittests/utils.js
=> fix: allow `dir` and `title` attributes

umap/static/umap/css/panel.css
=> fix: allow panel expanded mode in mobile

umap/static/umap/js/modules/caption.js, umap/static/umap/js/modules/global.js, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js, umap/tests/base.py, umap/tests/integration/test_caption.py, umap/tests/integration/test_map.py
And move caption in a dedicated module, as for browser, facets…
fix #1820
=> fix: display all layers in caption

umap/static/umap/js/umap.js
=> fix: do not autoclose panel blindly after map save

umap/static/umap/js/modules/browser.js, umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.core.js, umap/static/umap/js/umap.js, umap/static/umap/js/umap.layer.js
=> chore: replace DomUtil.classIf by classList.toggle

umap/static/umap/js/umap.js
=> fix: do not consider shortcuts if shift is also pressed

umap/static/umap/js/umap.controls.js
=> fix: error when clicking on the geolocate button

umap/static/umap/map.css
=> fix: invert star icons when map is starred or not

umap/static/umap/js/modules/utils.js, umap/static/umap/unittests/utils.js
Refs https://forum.openstreetmap.fr/t/umap-audio-video-et-panneau-lateral/2804/2
=> fix: allow audio and video tags (+attributes) in HTML

umap/static/umap/js/modules/global.js, umap/static/umap/js/modules/importer.js, umap/templates/umap/js.html
Just moving the file under modules/ so it can interact with other modules
=> chore: move importer to modules/

umap/static/umap/css/panel.css, umap/static/umap/map.css, umap/static/umap/vars.css
And refactor the way we set top/bottom of controls and panels.
=> fix: panel condensed height should never be bigger than screen

umap/static/umap/css/icon.css, umap/static/umap/css/panel.css, umap/static/umap/js/modules/caption.js
=> fix: caption title rendering on multiple lines

umap/static/umap/js/umap.layer.js
=> fix: show message in case of xml parsing error

umap/static/umap/js/modules/caption.js
This was broken in e6b4a54499ca547544d721ebdf5b3ff2b970e34e
fix #1874
=> fix: display layer in naturel order in caption

umap/static/umap/js/modules/importers/datasets.js, umap/tests/integration/test_import.py
=> feat: set layer name when importing from dataset

umap/static/umap/base.css
=> fix: remove custom styles for radio inputs

umap/static/umap/base.css, umap/static/umap/css/importers.css, umap/static/umap/css/panel.css
=> fix: CSS adjustments for importers

umap/static/umap/map.css, umap/static/umap/vars.css
broken by c0ecc3943973f9efcfb16ebe2b0a9600a0967a0d
=> fix: fix slideshow toolbar position and size

umap/static/umap/js/modules/utils.js, umap/static/umap/unittests/utils.js
We already have a h3 as title, both in the popup or in the panel
=> chore: smaller headings in descriptions

umap/static/umap/base.css
=> chore: change heading CSS size

umap/static/umap/js/umap.layer.js, umap/tests/integration/test_edit_polygon.py
=> fix: fix path disappearing when changing its datalayer

umap/static/umap/js/umap.js
=> fix: Distinction between clearing data vs. layers

umap/static/umap/content.css
=> fix: better spacing for the alert box, when activated

Makefile, biome.json, docs/contributing.md, package-lock.json, package.json, umap/storage.py
Documentation : https://biomejs.dev/guides/getting-started/
If you are using SublimeText: https://packagecontrol.io/packages/LSP-biome
=> chore: setup Biome to replace Prettier

umap/static/umap/js/modules/importers/overpass.js
And make it configurable in the same time.
=> fix: allow to search a French departement in Overpass importer

umap/static/umap/map.css
=> fix: make sure panels are above controls

umap/tests/integration/conftest.py, umap/tests/integration/test_datalayer.py
Also, define a custom page fixture so we can get console messages in the terminal.
=> try to fix toZoom and fromZoom randomly failing tests

umap/static/umap/css/tableeditor.css
Also, decrease line-height of header cells
=> fix: remove padding from table editor inputs

umap/static/umap/js/modules/utils.js, umap/static/umap/unittests/utils.js
cf https://github.com/umap-project/umap/issues/820#issuecomment-2227821746
(Also pass biome on js tests in a separate commit)
=> Fix variable pointing to null value displayed instead of the fallback

docs-users/fr/support/faq.md, docs-users/support/faq.md, umap/static/umap/js/umap.features.js, umap/tests/integration/test_view_marker.py
=> feat: add {layer} as popup variable (aka extended properties)

umap/static/umap/js/modules/formatter.js, umap/tests/fixtures/test_upload_georss.xml, umap/tests/integration/test_import.py
=> fix: fix georss import

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/rendering/ui.js, umap/static/umap/js/modules/schema.js, umap/static/umap/js/umap.controls.js, umap/tests/integration/test_draw_polygon.py
fix #1125
Refactor a bit the API and separation of concerns of our Feature and UI elements.
[Screencast from 2024-08-02 12-08-41.webm](https://github.com/user-attachments/assets/2d10a073-bac1-4524-a117-59f58bb211a3)
=> feat: allow to display a polygon "negative"

umap/static/umap/js/umap.controls.js, umap/static/umap/js/umap.js, umap/static/umap/map.css, umap/tests/integration/test_tilelayer.py
=> feat: add a "+" button in the tilelayer switcher

umap/static/umap/js/modules/formatter.js, umap/tests/integration/helpers.py, umap/tests/integration/test_draw_polygon.py, umap/tests/integration/test_draw_polyline.py, umap/tests/integration/test_import.py
=> fix: import GPX desc as description

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/rendering/layers/classified.js, umap/static/umap/js/modules/rendering/ui.js, umap/static/umap/js/modules/schema.js, umap/static/umap/js/umap.controls.js, umap/static/umap/map.css, umap/tests/fixtures/test_circles_layer.geojson, umap/tests/integration/test_circles_layer.py, umap/tests/integration/test_edit_datalayer.py
=> Add "Proportional Circles" layer type

umap/tests/integration/test_tilelayer.py
For reference: https://github.com/openstreetmap/operations/issues/737
=> Use preferred tile.openstreetmap.org URL

umap/static/umap/js/umap.controls.js
Otherwise the measure if wrong.
fix #2069
=> fix: correctly add drawn latlng when continuing line backward

umap/static/umap/js/umap.forms.js
Comparing `"null"` (in the HTML) and `null` (in the JS) was returning false.
=> fix: make sure to compare comparable values in ternary operators

umap/settings/base.py, umap/templates/umap/content_footer.html
=> fix: register fa-ir in LANG_INFO

docs-users/fr/support/faq.md, docs-users/support/faq.md, umap/static/umap/js/modules/rules.js, umap/tests/integration/test_conditional_rules.py
Also fix boolean behaviour (only true was working).
=> feat: add explicit empty/not empty check in conditional rules

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/tests/integration/test_browser.py
=> fix: filter feature by displayName by default

umap/static/umap/js/umap.controls.js, umap/tests/integration/test_draw_polyline.py
=> fix: delete shape from edit toolbar

umap/static/umap/js/modules/data/features.js, umap/tests/integration/test_draw_polyline.py
=> fix: fix merge lines on vertex click

umap/static/umap/js/modules/browser.js, umap/static/umap/js/modules/data/features.js, umap/tests/integration/test_cluster.py
=> fix: clicking feature in the browser would not open popup in cluster

umap/admin.py
=> feat: very minimal CSV export of users and maps in admin

umap/static/umap/js/modules/data/layer.js
=> fix: remoteData helpEntries were not on the right format

umap/static/umap/js/modules/autocomplete.js, umap/static/umap/js/modules/importers/communesfr.js
Otherwise when searching for a very commun name (like "Saint-Paul"), one may not find the right one among the x returned results.
=> feat: allow to search by code INSEE in communes importer

Makefile, pyproject.toml, umap/tests/integration/test_datalayer.py, umap/tests/integration/test_import.py, umap/tests/integration/test_map.py
I first thought about marking test as flaky one by one, but my impression is mainly all playwright test can become flacky, and we actually only see some as their appear in the list.
=> chore: use pytest-rerunfailed

umap/templates/umap/map_detail.html, umap/tests/test_map_views.py
=> fix: make sure maps of demo instances of uMap are no indexed

umap/models.py
Otherwise it will fail if src and dest are not on the same FS.
=> chore: use shutil.move instead of Path.rename to move to purgatory

docs-users/fr/tutorials/2-first-map.md
Change AgentConnect to ProConnect
=> docs: Change AgentConnect to ProConnect

.gitignore, Makefile, charts/umap/.helmignore, charts/umap/Chart.yaml, charts/umap/templates/_helpers.tpl, charts/umap/templates/deployment.yaml, charts/umap/templates/ingress.yaml, charts/umap/templates/pvc.yaml, charts/umap/templates/secret-config.yaml, charts/umap/templates/secret-env.yaml, charts/umap/templates/service.yaml, charts/umap/templates/serviceaccount.yaml, charts/umap/values.yaml
This helm chart allow to deploy umap on a Kubernetes cluster easily.
=> Add umap helm chart for Kubernetes deployment

umap/static/umap/content.css, umap/static/umap/vars.css, umap/templates/registration/login.html
Fixes https://github.com/umap-project/umap-dsfr/issues/21
Rel. https://github.com/umap-project/umap-dsfr/commit/24f23874f7877592ab68f296fb401f9bc9c4418c
=> Better login page styles and incentive

umap/static/umap/js/modules/rendering/map.js
=> feat: swap import and settings buttons in edit toolbar

umap/static/umap/js/modules/importers/geodatamine.js
Broken since the map split I guess.
=> fix: importer.map is undefined in geodatamine importer

umap/static/umap/js/modules/importers/cadastrefr.js
We remove the cancel button and change the accept label.
=> chore: change cadastrefr buttons

umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/global.js, umap/static/umap/js/modules/umap.js, umap/static/umap/js/umap.forms.js
Eg. the labelKey or filterKey input.
=> feat: add basic autocompletion on inputs expecting a field name

umap/static/umap/js/modules/ui/dialog.js
=> fix(#2355): correctly reset Dialog’s returnValue

umap/static/umap/css/popup.css, umap/static/umap/js/modules/rendering/template.js, umap/static/umap/map.css, umap/templates/umap/css.html
(And move popup related CSS to a dedicated file.)
cf #661
=> feat: display wikipedia link in OSM popup template when possible

umap/static/umap/js/modules/importer.js, umap/static/umap/js/modules/ui/dialog.js
=> feat: add a back button to importers dialog

umap/static/umap/js/modules/umap.js
=> fixup: fix save center and zoom

umap/static/umap/js/modules/data/layer.js, umap/tests/fixtures/test_upload_simple_marker.json, umap/tests/integration/test_import.py
cf https://github.com/umap-project/umap/pull/2363#discussion_r1882966275
=> feat: parse files in parallel at import when multiple

umap/static/umap/js/modules/rendering/map.js, umap/static/umap/js/umap.controls.js
=> fixup: fix tilelayer switch not saved anymore

biome.json
Seems to be working today, no damn idea why it is and it was not before.
=> chore: try to make biome ignore vendors/

docs/config/storage.md, umap/templates/base.html, umap/templates/umap/components/alerts/alert.html, umap/templates/umap/css.html, umap/templates/umap/js.html, umap/templates/umap/map_init.html, umap/templates/umap/user_dashboard.html
When using django-storage S3, this will escape the final static URL,
containing query string (so & will become &amp;).
=> fix: do not autoescape static tag

umap/static/umap/css/bar.css, umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/sync/engine.js, umap/static/umap/js/modules/sync/websocket.js, umap/static/umap/js/modules/umap.js, umap/static/umap/unittests/sync.js, umap/websocket_server.py
This is a port of this PR: #2235
(But it was easier to copy-paste than rebase, given the split of umap.js and co.)
=> feat: reconnect websocket on disconnection

docs-users/fr/support/faq.md, docs-users/support/faq.md, umap/decorators.py, umap/static/umap/content.css, umap/static/umap/img/logo_lightcyan.svg, umap/templates/403.html, umap/templates/404.html, umap/templates/40x.html
=> wip: add a 403.html template

umap/static/umap/js/umap.controls.js
cf https://github.com/umap-project/umap/issues/2392#issuecomment-2561151836
=> fix: fix create marker from search result

umap/static/umap/js/modules/umap.js
=> fix: fix startMarker/Polyline/Polygon on right click

umap/static/umap/js/modules/umap.js, umap/static/umap/js/modules/utils.js
=> fix: do not consume ctrl-Z in textarea or input

umap/static/umap/js/modules/rendering/icon.js
=> fix: fix circle icon no longer hihlighted

umap/static/umap/js/modules/data/layer.js
=> fix: display a more usefull message when error in remote data

umap/static/umap/js/modules/utils.js, umap/static/umap/unittests/utils.js
fix #2457
Thoughts @jschleic ?
=> fix: correctly parse http link including another http link in the path

umap/static/umap/js/modules/form/fields.js, umap/static/umap/js/modules/schema.js
=> fix: allow to set choices for a nullablechoices field

umap/static/umap/css/bar.css, umap/static/umap/css/tooltip.css, umap/static/umap/js/modules/sync/engine.js, umap/static/umap/js/modules/ui/bar.js, umap/static/umap/js/modules/ui/base.js, umap/static/umap/js/modules/ui/tooltip.js, umap/static/umap/js/modules/umap.js, umap/static/umap/vars.css, umap/tests/integration/test_draw_polygon.py
=> Sync show usernames

umap/static/umap/css/form.css, umap/static/umap/js/modules/caption.js, umap/static/umap/vars.css
Also make created/modified lower case on caption.
cf #2424
cf #2442
cc @Aurelie-Jallut
=> chore: smaller star button and invert author and dates

.github/workflows/test-docs.yml
=> chore: run the CI even for PR not targetting master (and remove doc build twice)

umap/static/umap/js/modules/form/fields.js
=> fix: use default value from schema for non inheritable fields

umap/static/umap/css/icon.css, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/umap.js
=> chore: use template for map advanced buttons (and fix icons)

umap/sync/app.py
cf https://umap.sentry.io/issues/6331841272/
=> chore: do not try to disconnect ws if not connected

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js
This will open a new page with only this given layer shown.
=> feat: add a quick link to layer's permalink

umap/settings/base.py, umap/static/umap/base.css, umap/static/umap/nav.css, umap/templates/umap/content_footer.html
And underline for external links otherwise the new green color is too close to the text one to clearly identify links.
=> a11y: switch to better contrasted links

umap/static/umap/js/modules/data/features.js
=> fix: cast value to string before calling trim

umap/static/umap/css/dialog.css, umap/static/umap/js/modules/help.js
=> feat: add titles in the text formatting dialog

umap/static/umap/css/bar.css, umap/static/umap/js/modules/ui/bar.js, umap/tests/integration/test_browser.py, umap/tests/integration/test_conditional_rules.py, umap/tests/integration/test_edit_datalayer.py, umap/tests/integration/test_edit_polygon.py, umap/tests/integration/test_save.py, umap/tests/integration/test_websocket_sync.py
=> chore: refine undo/redo buttons

umap/static/umap/base.css, umap/static/umap/content.css, umap/static/umap/css/bar.css, umap/static/umap/css/form.css, umap/static/umap/map.css, umap/static/umap/vars.css, umap/templates/umap/search_bar.html
=> chore: refine main search form

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/rendering/ui.js, umap/static/umap/js/modules/umap.js
=> fix: properly call endEdit for markers

umap/static/umap/map.css
Before:
After:
(Please don't ask :p )
=> fix: fix text overflow on search results

umap/views.py
If user is authenticated.
We do not display alert messages on the home page.
=> chore: redirect to user dashboard after map delete

umap/static/umap/js/modules/browser.js
=> feat: hidden download button in browser when embedControl=false

umap/static/umap/css/bar.css, umap/templates/umap/design_system.html
=> chore: more design system elements

umap/static/umap/js/modules/browser.js, umap/static/umap/map.css, umap/tests/integration/test_edit_map.py, umap/tests/integration/test_facets_browser.py, umap/tests/integration/test_import.py, umap/tests/integration/test_map.py, umap/tests/integration/test_websocket_sync.py
=> chore: use details/summary for datalayers boxes in browser

umap/static/umap/js/modules/help.js
=> chore: add help entry for collaborative editing setting

umap/models.py
=> fix: fix label not shown on map preview

umap/tests/test_dashboard.py, umap/views.py
We cannot call annotate after using a union.
=> fix: fix map search in dashboard

umap/static/umap/js/modules/ui/bar.js
=> chore: add "load template" button in help dialog

docs/config/settings.md, umap/settings/base.py, umap/static/umap/js/modules/help.js, umap/static/umap/map.css, umap/views.py
=> chore: add external resources links in help dialog

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/sync/updaters.js, umap/static/umap/js/modules/tableeditor.js, umap/tests/integration/test_tableeditor.py
=> fix: allow to undo/redo renaming or deleting a property

umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/rendering/layers/classified.js, umap/static/umap/js/modules/rules.js, umap/static/umap/js/modules/ui/panel.js, umap/static/umap/js/modules/umap.js, umap/tests/integration/test_conditional_rules.py
=> feat: allow conditional rules on datalayer

umap/static/umap/css/form.css, umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/tableeditor.js, umap/tests/integration/test_edit_marker.py
=> feat: allow to add a new property from feature edit panel

umap/static/umap/js/modules/templates.js
=> chore: remove description from templates list

umap/static/umap/css/icon.css, umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/form/fields.js, umap/static/umap/js/modules/rendering/layers/classified.js, umap/static/umap/js/modules/rules.js, umap/static/umap/js/modules/schema.js, umap/static/umap/js/modules/sync/updaters.js, umap/static/umap/js/modules/tableeditor.js, umap/static/umap/js/modules/ui/panel.js, umap/static/umap/js/modules/umap.js, umap/tests/base.py, umap/tests/integration/test_edit_marker.py, umap/tests/integration/test_export_map.py, umap/tests/integration/test_optimistic_merge.py, umap/tests/integration/test_tableeditor.py
=> Fields management

umap/static/umap/js/modules/form/fields.js, umap/tests/integration/test_edit_datalayer.py
And add an help tooltip.
fix #2425
=> fix: only make layer name editable on double click

umap/static/umap/js/modules/browser.js, umap/static/umap/js/modules/data/features.js, umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/facets.js, umap/static/umap/js/modules/managers.js, umap/static/umap/js/modules/rendering/layers/classified.js, umap/static/umap/js/modules/rendering/map.js, umap/static/umap/js/modules/slideshow.js, umap/static/umap/js/modules/sync/updaters.js, umap/static/umap/js/modules/tableeditor.js, umap/static/umap/js/modules/umap.js, umap/tests/integration/test_optimistic_merge.py
Also remove the use of `L.stamp(feature)` and use `feature.id` instead.
=> chore: add FeatureManager

umap/static/umap/css/form.css, umap/static/umap/js/modules/importer.js, umap/static/umap/js/modules/importers/opendata.js
Featuring open data for Saint-Pierre et Miquelon! :)
=> feat: add connector for Prodige data portals

umap/static/umap/js/modules/data/layer.js, umap/static/umap/js/modules/formatter.js, umap/static/umap/js/modules/managers.js, umap/static/umap/js/modules/share.js, umap/static/umap/js/modules/umap.js, umap/tests/integration/test_export_map.py
fix #2807
uMap full backup and single datalayer download are not affected by this change.
=> fix: exports should respect filters

charts/umap/Chart.yaml, charts/umap/templates/deployment.yaml
Avoids one redirection for every health check
=> fix(helm): use stats endpoint for nginx probe

umap/static/umap/js/modules/rendering/layers/cluster.js
We need this slider start sooner
=> Minimum cluster value

umap/static/umap/css/bar.css, umap/static/umap/css/panel.css
=> fix: keep panels buttons accessible on small screens

umap/static/umap/js/modules/formatter.js, umap/tests/integration/test_import.py
We want to use either "WKT" or "wkt" or "Geom".
=> fix: case insensitive match of CSV geom column

umap/static/umap/css/bar.css, umap/static/umap/css/contextmenu.css, umap/static/umap/css/form.css, umap/static/umap/css/icon.css, umap/static/umap/js/components/alerts/alert.css, umap/static/umap/js/modules/caption.js, umap/static/umap/js/modules/permissions.js, umap/static/umap/js/modules/rendering/controls.js, umap/static/umap/js/modules/ui/bar.js, umap/static/umap/js/modules/umap.js, umap/static/umap/map.css, umap/static/umap/vars.css, umap/templates/umap/components/alerts/alert.html, umap/tests/integration/test_anonymous_owned_map.py, umap/tests/integration/test_basics.py, umap/tests/integration/test_draw_polygon.py, umap/urls.py, umap/views.py
=> Allow to login from the map page

umap/static/umap/js/components/alerts/alert.js, umap/static/umap/js/modules/domutils.js, umap/static/umap/js/modules/permissions.js, umap/static/umap/js/modules/ui/bar.js, umap/static/umap/js/modules/umap.js, umap/static/umap/vars.css, umap/templates/umap/components/alerts/alert.html, umap/tests/integration/test_anonymous_owned_map.py
=> feat: allow to attach map to account after creation

umap/static/umap/js/modules/rendering/template.js
https://forum.openstreetmap.fr/t/umap-valoriser-relier-vers-les-donnees-wikidata/37615/7
=> feat: add a Mapillary link when tag is present, in OSM popup template

umap/static/umap/js/modules/rendering/template.js
cf https://forum.openstreetmap.fr/t/umap-valoriser-relier-vers-les-donnees-wikidata/37615/8
=> feat: display image tag when present in OSM template

umap/static/umap/js/modules/rendering/template.js
=> fix: only show Wikipedia intro, and add credit and full link in footer

umap/static/umap/js/modules/importers/openrouteservice.js
Also, sort features by duration desc, so to have smaller polygons on top.
fix #2905
=> feat: add duration and profile in isochrone data
